/* ==========================================================
   LearnWater — Word Lab words (Kids Corner)
   Kid-friendly water words for ages 6–12. Used by the Word Lab
   page (kids-words.html) and by Greg, who can explain any of them.
   Each word: [word, emoji, how to say it, meaning, example, group]
   Groups are listed in KIDS_WORD_GROUPS below.
   ========================================================== */
window.KIDS_WORD_GROUPS = [
  { id: 'cycle',   icon: '🔄', name: 'Water Cycle' },
  { id: 'weather', icon: '⛅', name: 'Weather' },
  { id: 'earth',   icon: '🌎', name: 'Earth & Oceans' },
  { id: 'life',    icon: '🐸', name: 'Living Things' },
  { id: 'science', icon: '🧪', name: 'Science Words' },
  { id: 'clean',   icon: '🚰', name: 'Clean Water' },
  { id: 'save',    icon: '💚', name: 'Saving Water' }
];

window.KIDS_WORDS = [
  /* ---------- Water cycle ---------- */
  ["Water cycle", "🔄", "WAH-ter SY-kul", "The never-ending trip water takes. It rises into the sky, makes clouds, falls back down as rain or snow, and flows to rivers, lakes, and oceans to start all over again.", "The water in your glass has gone around the water cycle many, many times!", "cycle"],
  ["Evaporation", "☀️", "ee-vap-uh-RAY-shun", "When the sun warms liquid water and it turns into an invisible gas called water vapor that floats up into the air.", "A puddle disappears on a sunny day because of evaporation.", "cycle"],
  ["Condensation", "🥶", "kon-den-SAY-shun", "When water vapor cools down and turns back into tiny drops of liquid water.", "The drops on the outside of a glass of ice water are condensation.", "cycle"],
  ["Precipitation", "🌧️", "prih-sip-ih-TAY-shun", "Water that falls from clouds to the ground: rain, snow, sleet, or hail.", "Snow is precipitation that falls when the air is very cold.", "cycle"],
  ["Collection", "🏞️", "kuh-LEK-shun", "The part of the water cycle where water gathers in oceans, lakes, rivers, and under the ground.", "After a storm, rain collects in creeks that flow to the river.", "cycle"],
  ["Transpiration", "🌿", "tran-spuh-RAY-shun", "When plants let water vapor out through tiny holes in their leaves. It's a little like plants sweating!", "A big oak tree can give off about 40,000 gallons of water in a year.", "cycle"],
  ["Water vapor", "💨", "WAH-ter VAY-per", "Water in its gas form. It's invisible and floats in the air all around us.", "When you breathe on a cold window, the foggy spot comes from water vapor in your breath.", "cycle"],
  ["Runoff", "🌊", "RUN-off", "Rain or melted snow that flows over the ground instead of soaking in, and runs into streams, rivers, and lakes.", "Runoff from a parking lot can carry trash and oil into a creek.", "cycle"],
  ["Infiltration", "🕳️", "in-fil-TRAY-shun", "When water soaks down into the ground.", "Rain on a grassy yard infiltrates into the soil instead of running off.", "cycle"],
  ["Groundwater", "⛲", "GROWND-wah-ter", "Water stored under the ground in the tiny spaces between bits of soil, sand, and rock.", "Most towns in Mississippi drink groundwater pumped up from deep wells.", "cycle"],
  ["Sublimation", "🧊", "sub-lih-MAY-shun", "When ice or snow turns straight into water vapor without melting into a liquid first.", "On cold, sunny, windy days, snow piles can shrink by sublimation.", "cycle"],
  ["Water table", "📏", "WAH-ter TAY-bul", "The top of the underground layer where the ground is soaked full of water.", "Dig a deep hole near a lake and water seeps in when you reach the water table.", "cycle"],
  ["Snowmelt", "🏔️", "SNOH-melt", "Water that comes from melting snow.", "In spring, snowmelt from the mountains fills up rivers.", "cycle"],
  ["Dew", "🌱", "DOO", "Little drops of water that form on grass and leaves on cool mornings. It's condensation!", "Your shoes get wet when you walk through grass covered in morning dew.", "cycle"],
  ["Frost", "❄️", "FRAWST", "Ice crystals that form on cold surfaces when water vapor freezes.", "Frost made sparkly patterns on the car window.", "cycle"],

  /* ---------- Weather ---------- */
  ["Cloud", "☁️", "KLOWD", "Billions of tiny water drops or ice crystals floating together in the sky.", "One puffy cloud can weigh about 1.1 million pounds, as much as 100 elephants!", "weather"],
  ["Rain", "🌧️", "RAYN", "Drops of liquid water that fall from clouds.", "Raindrops aren't shaped like tears. Big ones look more like the top of a hamburger bun!", "weather"],
  ["Snow", "🌨️", "SNOH", "Ice crystals that fall from clouds when the air is below freezing.", "Most snowflakes have six sides or six arms.", "weather"],
  ["Hail", "🧊", "HAYL", "Balls of ice that grow inside tall thunderstorm clouds and then fall to the ground.", "Hailstones can be as small as a pea or bigger than a baseball!", "weather"],
  ["Sleet", "🌨️", "SLEET", "Raindrops that freeze into little ice pellets before they reach the ground.", "Sleet bounces when it hits the sidewalk.", "weather"],
  ["Fog", "🌫️", "FOG", "A cloud that forms down low, right near the ground.", "In thick fog, you might not be able to see across the street.", "weather"],
  ["Humidity", "💦", "hyoo-MID-ih-tee", "How much water vapor is in the air.", "Mississippi summers feel sticky because the humidity is high.", "weather"],
  ["Drought", "🏜️", "DROWT", "A long time with much less rain than normal, so the land, lakes, and rivers start to dry out.", "During a drought, towns may ask people to save water.", "weather"],
  ["Flood", "🌊", "FLUD", "When water overflows onto land that is usually dry.", "Many days of heavy rain can make a river flood.", "weather"],
  ["Rainbow", "🌈", "RAYN-boh", "A colorful arc that appears when sunlight shines through raindrops, which bend the light and split it into colors.", "To see a rainbow, stand with the sun behind you and the rain in front of you.", "weather"],
  ["Thunderstorm", "⛈️", "THUN-der-storm", "A storm with rain, lightning, and thunder, made by very tall clouds.", "When thunder roars, go indoors!", "weather"],
  ["Rain gauge", "📏", "RAYN gayj", "A tool that measures how much rain has fallen.", "Our rain gauge showed 2 inches of rain after the storm.", "weather"],
  ["Forecast", "📺", "FOR-kast", "A prediction of what the weather will be like.", "The forecast says there's a big chance of rain tomorrow.", "weather"],
  ["Hurricane", "🌀", "HUR-ih-kayn", "A huge spinning storm that forms over warm ocean water, with very strong winds and heavy rain.", "Hurricanes can bring big waves and flooding to the Mississippi coast.", "weather"],
  ["Temperature", "🌡️", "TEM-pruh-cher", "How hot or cold something is.", "Water freezes at 32°F and boils at 212°F.", "weather"],
  ["Meteorologist", "🧑‍🔬", "mee-tee-uh-ROL-uh-jist", "A scientist who studies the weather and makes forecasts.", "The meteorologist on TV warned everyone about the storm.", "weather"],

  /* ---------- Earth & oceans ---------- */
  ["Ocean", "🌊", "OH-shun", "A huge body of salt water. Oceans cover about 71% of Earth.", "The oceans hold about 97% of all the water on Earth.", "earth"],
  ["Lake", "🏞️", "LAYK", "A large body of water with land all around it.", "Most lakes are fresh water, but a few, like the Great Salt Lake, are salty.", "earth"],
  ["Pond", "🪷", "POND", "A small, shallow body of still water.", "Frogs lay their eggs in ponds.", "earth"],
  ["River", "🛶", "RIV-er", "A large stream of fresh water that flows across the land toward a lake, sea, or ocean.", "The Mississippi River is about 2,340 miles long!", "earth"],
  ["Stream", "💧", "STREEM", "A small river. People also call it a creek or a brook.", "Little streams join together to make big rivers.", "earth"],
  ["Watershed", "🗺️", "WAH-ter-shed", "All the land where rain and snowmelt drain into the same river, lake, or ocean.", "Everyone lives in a watershed. What goes down your street's storm drain ends up in a river.", "earth"],
  ["Wetland", "🦆", "WET-land", "Land that is soggy or covered with shallow water, like a swamp or marsh. Wetlands clean water and are home to many animals.", "Wetlands work like sponges that soak up flood water.", "earth"],
  ["Swamp", "🐊", "SWAMP", "A wetland with trees growing in it, like cypress trees.", "Alligators live in Mississippi swamps.", "earth"],
  ["Marsh", "🌾", "MARSH", "A wetland full of grasses and reeds instead of trees.", "Herons wade through the marsh looking for fish.", "earth"],
  ["Bayou", "🐢", "BY-oo", "A slow-moving, marshy creek or river, common in the southern United States.", "Turtles sun themselves on logs in the bayou.", "earth"],
  ["Estuary", "🦀", "ES-choo-air-ee", "A place where a river meets the sea, and fresh water mixes with salt water.", "Baby shrimp and crabs grow up in estuaries.", "earth"],
  ["Glacier", "🏔️", "GLAY-sher", "A giant, slow-moving river of ice on land, made from snow that piled up for many years.", "Glaciers and ice sheets hold most of Earth's fresh water.", "earth"],
  ["Iceberg", "🧊", "ICE-burg", "A big chunk of ice that broke off a glacier and floats in the sea.", "Most of an iceberg is hidden under the water.", "earth"],
  ["Aquifer", "🪨", "AK-wuh-fer", "A layer of sand, gravel, or rock under the ground that holds lots of water, like a giant sponge.", "Mississippi has many aquifers deep under the ground.", "earth"],
  ["Spring", "⛲", "SPRING", "A place where groundwater flows out of the ground all by itself.", "Long ago, people built towns near springs so they'd have fresh water.", "earth"],
  ["Geyser", "♨️", "GUY-zer", "A hot spring that shoots hot water and steam up into the air.", "Old Faithful in Yellowstone National Park erupts about every hour and a half.", "earth"],
  ["Delta", "🔺", "DEL-tuh", "Flat land made of mud and sand that a river drops where it slows down at its mouth.", "The Mississippi River built a huge delta in Louisiana where it meets the Gulf.", "earth"],
  ["Fresh water", "💧", "FRESH WAH-ter", "Water with very little salt in it, like most rivers, lakes, and groundwater. Only about 3% of Earth's water is fresh.", "People, pets, and farm animals need fresh water to drink.", "earth"],
  ["Salt water", "🧂", "SAWLT WAH-ter", "Water with lots of salt mixed in, like ocean water.", "Never drink salt water. It makes you even thirstier!", "earth"],
  ["Reservoir", "🏞️", "REZ-er-vwar", "A lake, often made by building a dam, that stores water for drinking, farming, or making electricity.", "Some cities get their drinking water from a reservoir.", "earth"],
  ["Dam", "🧱", "DAM", "A wall built across a river to hold back water.", "Beavers build dams out of sticks and mud!", "earth"],
  ["Tide", "🌙", "TIDE", "The slow rise and fall of the ocean's water along the shore each day, caused mostly by the Moon's pull.", "At low tide, you can find crabs and shells on the beach.", "earth"],
  ["Erosion", "🏜️", "ee-ROH-zhun", "When water, wind, or ice slowly wears away rock and soil and carries it somewhere else.", "The Grand Canyon was carved by erosion from the Colorado River.", "earth"],
  ["Sediment", "🟤", "SED-uh-ment", "Sand, mud, and bits of rock that water carries and then drops somewhere else.", "Muddy river water is full of sediment.", "earth"],
  ["Floodplain", "🌾", "FLUD-playn", "Flat land next to a river that gets covered with water when the river floods.", "Floodplain soil is great for growing crops.", "earth"],
  ["Wave", "🏄", "WAYV", "A moving bump of water on top of the ocean or a lake, usually pushed by the wind.", "Surfers ride big waves to the beach.", "earth"],

  /* ---------- Living things ---------- */
  ["Habitat", "🏡", "HAB-ih-tat", "The natural home of a plant or animal.", "A pond is a habitat for frogs, fish, and dragonflies.", "life"],
  ["Aquatic", "🐟", "uh-KWAT-ik", "Living or growing in water.", "Fish and water lilies are aquatic.", "life"],
  ["Amphibian", "🐸", "am-FIB-ee-un", "An animal, like a frog or salamander, that starts life in water and can live on land when it grows up.", "Frogs are amphibians that start out as tadpoles.", "life"],
  ["Tadpole", "🐸", "TAD-pohl", "A baby frog or toad that lives in water, breathes with gills, and has a tail.", "A tadpole slowly grows legs and turns into a frog.", "life"],
  ["Gills", "🐠", "GILZ", "Body parts that let fish breathe oxygen from the water.", "Water flows over a fish's gills as it swims.", "life"],
  ["Plankton", "🦐", "PLANK-tun", "Tiny plants and animals that drift in the water. Many are too small to see.", "Some huge whales eat tiny plankton.", "life"],
  ["Algae", "🟢", "AL-jee", "Simple plant-like living things that grow in water and make oxygen.", "The green scum on top of a pond is usually algae.", "life"],
  ["Ecosystem", "🌳", "EE-koh-sis-tum", "All the living things in a place, plus the water, soil, and air around them, working together.", "A river ecosystem has fish, bugs, plants, birds, and clean water.", "life"],
  ["Food chain", "🔗", "FOOD chayn", "The path of who eats whom in nature.", "Algae is eaten by bugs, bugs are eaten by fish, and fish are eaten by herons.", "life"],
  ["Coral reef", "🪸", "KOR-ul REEF", "An underwater structure built by tiny ocean animals called coral. Reefs are home to lots of sea life.", "Colorful fish hide in the coral reef.", "life"],
  ["Photosynthesis", "🌱", "foh-toh-SIN-thuh-sis", "How plants use sunlight, water, and air to make their own food, giving off oxygen as they do it.", "Plants need water for photosynthesis, so don't forget to water them!", "life"],
  ["Roots", "🌳", "ROOTS", "The parts of a plant that grow under the ground and soak up water.", "A tree's roots can spread out wider than its branches.", "life"],
  ["Hydration", "🥤", "hy-DRAY-shun", "Having enough water in your body.", "Drink water before, during, and after you play to stay hydrated.", "life"],
  ["Dehydration", "🥵", "dee-hy-DRAY-shun", "When your body doesn't have enough water. It can make you tired, dizzy, or give you a headache.", "On hot days, drink water often to avoid dehydration.", "life"],
  ["Thirst", "😮‍💨", "THURST", "Your body's signal that it needs water.", "After running around outside, you might feel thirst.", "life"],
  ["Sweat", "💦", "SWET", "Salty water that comes out of your skin to cool you down.", "You sweat when you exercise or when it's hot.", "life"],
  ["Kidneys", "🫘", "KID-neez", "Two bean-shaped organs that clean your blood. They need plenty of water to do their job.", "Drinking water helps your kidneys work well.", "life"],
  ["Nutrients", "🥕", "NOO-tree-ents", "The good stuff living things need to grow. Too many nutrients from fertilizer can make algae grow out of control in lakes.", "Plants take nutrients from the soil with water.", "life"],

  /* ---------- Science words ---------- */
  ["Molecule", "🔬", "MOL-uh-kyool", "The tiniest piece of a substance. A water molecule is made of 2 hydrogen atoms and 1 oxygen atom.", "One drop of water has more molecules than there are stars in our galaxy!", "science"],
  ["Atom", "⚛️", "AT-um", "A super tiny building block that everything is made of.", "Atoms are so small that millions could fit on the period at the end of this sentence.", "science"],
  ["H₂O", "💧", "AYCH-too-OH", "The science name for water: two hydrogen atoms (H) stuck to one oxygen atom (O).", "Scientists write water as H₂O.", "science"],
  ["Hydrogen", "🎈", "HY-druh-jen", "The lightest element in the universe. Every water molecule has two hydrogen atoms.", "The Sun is made mostly of hydrogen.", "science"],
  ["Oxygen", "🫧", "OK-sih-jen", "A gas people and animals need to breathe. Every water molecule has one oxygen atom.", "Fish breathe oxygen that is mixed into the water.", "science"],
  ["Solid", "🧊", "SOL-id", "A state of matter that keeps its own shape. Ice is solid water.", "An ice cube is a solid.", "science"],
  ["Liquid", "💧", "LIK-wid", "A state of matter that flows and takes the shape of its container.", "Pour liquid water into a cup and it takes the cup's shape.", "science"],
  ["Gas", "💨", "GAS", "A state of matter that spreads out to fill any space. Water vapor is water as a gas.", "Steam from a pot of boiling water spreads out as a gas.", "science"],
  ["States of matter", "🧊", "STAYTS uv MAT-er", "The three main forms things come in: solid, liquid, and gas. Water is the only common thing found naturally in all three on Earth.", "Ice, water, and water vapor are the three states of water.", "science"],
  ["Freezing point", "🥶", "FREE-zing POYNT", "The temperature where liquid water turns into ice: 32°F (0°C).", "Lakes can freeze when the air stays below the freezing point.", "science"],
  ["Boiling point", "🫕", "BOY-ling POYNT", "The temperature where water bubbles and turns into steam: 212°F (100°C) at sea level.", "Pasta cooks in water heated to the boiling point.", "science"],
  ["Melting", "🫠", "MEL-ting", "When a solid, like ice, warms up and turns into a liquid.", "An ice pop starts melting on a hot day.", "science"],
  ["Freezing", "🥶", "FREE-zing", "When a liquid cools down and turns into a solid.", "Freezing juice in a tray makes juice cubes.", "science"],
  ["Steam", "♨️", "STEEM", "Very hot water vapor. The white cloud above boiling water is tiny drops of water forming as the steam cools.", "Steam rises from a hot bowl of soup.", "science"],
  ["Density", "⚖️", "DEN-sih-tee", "How tightly packed the stuff in something is. Things that are less dense float on things that are more dense.", "Ice is less dense than liquid water, so ice cubes float!", "science"],
  ["Buoyancy", "🛟", "BOY-un-see", "The upward push water gives to things in it. It's why boats and ducks float.", "Buoyancy makes it easier to lift a friend in a swimming pool.", "science"],
  ["Float", "🦆", "FLOHT", "To stay on top of a liquid instead of sinking.", "A rubber duck floats in the bathtub.", "science"],
  ["Sink", "⚓", "SINK", "To go down to the bottom of a liquid.", "A rock sinks to the bottom of a pond.", "science"],
  ["Surface tension", "🕷️", "SUR-fis TEN-shun", "Water molecules hold on tight at the top of the water, making a thin, stretchy skin.", "Surface tension lets water striders walk on water!", "science"],
  ["Dissolve", "🧂", "dih-ZOLV", "When something mixes into water so completely that you can't see it anymore, like sugar or salt.", "Stir sugar into lemonade and it dissolves.", "science"],
  ["Solution", "🥤", "suh-LOO-shun", "A mixture where one thing is dissolved evenly in another, like salt dissolved in water.", "Ocean water is a solution of salt and water.", "science"],
  ["Universal solvent", "🥄", "yoo-nuh-VER-sul SOL-vent", "A nickname for water, because it can dissolve more things than any other liquid.", "Water is called the universal solvent because it dissolves so many things.", "science"],
  ["Absorb", "🧽", "ub-ZORB", "To soak up a liquid.", "A sponge absorbs water.", "science"],
  ["Capillary action", "🌷", "KAP-uh-lair-ee AK-shun", "Water climbing up through tiny spaces, like up a paper towel or a plant's stem.", "Put celery in colored water and capillary action pulls the color up the stalk.", "science"],
  ["pH", "🧪", "pee-AYCH", "A scale from 0 to 14 that shows if something is an acid or a base. Pure water is 7, right in the middle.", "Lemon juice has a low pH because it's an acid.", "science"],
  ["Acid", "🍋", "AS-id", "Something with a pH below 7. Many acids taste sour.", "Lemon juice and vinegar are acids.", "science"],
  ["Base", "🧼", "BAYS", "Something with a pH above 7. Bases often feel slippery.", "Baking soda and soap are bases.", "science"],
  ["Hypothesis", "💡", "hy-POTH-uh-sis", "A smart guess a scientist makes and then tests with an experiment.", "My hypothesis is that ice melts faster in salt water.", "science"],
  ["Experiment", "🧪", "ik-SPER-uh-ment", "A test scientists do to find out if a hypothesis is right.", "We did an experiment to see which towel soaks up the most water.", "science"],
  ["Observe", "👀", "ub-ZURV", "To watch something carefully and notice details.", "Scientists observe their experiments and write down what they see.", "science"],
  ["Microscope", "🔬", "MY-kruh-skohp", "A tool that makes tiny things look big so we can see them.", "Under a microscope, a drop of pond water is full of tiny living things.", "science"],
  ["Germs", "🦠", "JURMZ", "Tiny living things, like some bacteria and viruses, that can make people sick.", "Washing your hands with soap and water gets rid of germs.", "science"],
  ["Bacteria", "🦠", "bak-TEER-ee-uh", "Tiny living things made of just one cell. Some are helpful, and some can make you sick.", "Helpful bacteria in your belly help you digest food.", "science"],
  ["Gallon", "🥛", "GAL-un", "A way to measure liquid. A gallon of water weighs about 8.34 pounds!", "A big jug of milk holds one gallon.", "science"],
  ["Volume", "🫙", "VOL-yoom", "How much space something takes up. We measure water volume in cups, gallons, and liters.", "The volume of a bathtub is about 40 to 50 gallons.", "science"],

  /* ---------- Clean water ---------- */
  ["Water treatment plant", "🏭", "WAH-ter TREET-ment PLANT", "A place where workers clean water from rivers, lakes, or wells to make it safe to drink.", "The water treatment plant cleans millions of gallons every day.", "clean"],
  ["Water operator", "👷", "WAH-ter OP-er-ay-ter", "A trained, licensed worker who runs a water system and tests the water to keep it safe.", "Water operators check the water every day, even on holidays.", "clean"],
  ["Filter", "🧽", "FIL-ter", "Something that lets water pass through but catches dirt and bits, like layers of sand, gravel, and charcoal.", "A coffee filter lets the coffee through but catches the grounds.", "clean"],
  ["Coagulation", "🧲", "koh-ag-yuh-LAY-shun", "A cleaning step where a special chemical is added to water to make tiny bits of dirt stick together.", "Coagulation turns tiny specks of dirt into bigger clumps.", "clean"],
  ["Floc", "☁️", "FLOK", "The fluffy clumps of dirt that form during water treatment, so they can sink or be filtered out.", "The floc looked like fluffy snowflakes in the tank.", "clean"],
  ["Sedimentation", "⬇️", "sed-uh-men-TAY-shun", "A cleaning step where water sits still so heavy clumps of dirt sink to the bottom.", "During sedimentation, the dirt settles like sand in a jar.", "clean"],
  ["Disinfection", "🛡️", "dis-in-FEK-shun", "Killing germs in water so it's safe to drink, usually with chlorine or ultraviolet (UV) light.", "Disinfection is the last cleaning step before water goes to homes.", "clean"],
  ["Chlorine", "🧪", "KLOR-een", "A chemical added to drinking water in a tiny amount to kill germs. It's also used to keep swimming pools clean.", "A little chlorine keeps germs out of the water all the way to your faucet.", "clean"],
  ["Fluoride", "🦷", "FLOR-ide", "A mineral that some towns add to drinking water in a tiny amount to help keep teeth strong.", "Fluoride is also in most toothpaste.", "clean"],
  ["Well", "🪣", "WEL", "A deep hole drilled into the ground to pump up groundwater.", "Some wells in Mississippi are more than 1,000 feet deep!", "clean"],
  ["Pump", "⚙️", "PUMP", "A machine that pushes water through pipes or lifts it up from a well.", "A pump sends water from the well up to the water tower.", "clean"],
  ["Water tower", "🗼", "WAH-ter TOW-er", "A tall tank that holds water up high, so gravity pushes it through pipes to homes with good pressure.", "Many towns paint their name on their water tower.", "clean"],
  ["Water main", "🚇", "WAH-ter MAYN", "A big pipe under the street that carries clean water to many homes.", "Workers fixed a broken water main under the road.", "clean"],
  ["Water pressure", "💪", "WAH-ter PRESH-er", "How hard water pushes through pipes.", "Good water pressure makes a strong shower.", "clean"],
  ["Plumbing", "🔧", "PLUM-ing", "All the pipes, faucets, toilets, and drains in a building.", "A plumber fixes problems with plumbing.", "clean"],
  ["Faucet", "🚰", "FAW-sit", "The tap you turn on to get water.", "Turn off the faucet while you brush your teeth.", "clean"],
  ["Water meter", "🔢", "WAH-ter MEE-ter", "A device that measures how much water a home or building uses.", "The water meter counts every gallon that comes into your house.", "clean"],
  ["Fire hydrant", "🚒", "FIRE HY-drant", "A pipe outlet near the street where firefighters hook up hoses to get water.", "Hydrant caps are painted different colors to show how much water they can give.", "clean"],
  ["Potable", "🥛", "POH-tuh-bul", "Safe to drink.", "The water from your kitchen faucet is potable water.", "clean"],
  ["Contaminant", "☣️", "kun-TAM-uh-nunt", "Something in water that shouldn't be there and could make it unsafe, like germs or harmful chemicals.", "Water operators test for contaminants to keep water safe.", "clean"],
  ["Pollution", "🛢️", "puh-LOO-shun", "Harmful stuff, like trash, oil, or chemicals, that makes water, air, or land dirty.", "Picking up litter helps stop pollution in our creeks.", "clean"],
  ["Turbidity", "🥤", "ter-BID-ih-tee", "How cloudy water is. Clear water has low turbidity.", "After a big rain, river water has high turbidity.", "clean"],
  ["Wastewater", "🚽", "WAYST-wah-ter", "Used water that goes down drains and toilets. It gets cleaned at a treatment plant before going back to a river.", "Wastewater from our homes travels through sewer pipes.", "clean"],
  ["Sewer", "🕳️", "SOO-er", "Underground pipes that carry wastewater away from homes and buildings.", "The sewer carries water from your bathtub drain to the treatment plant.", "clean"],
  ["Storm drain", "🌧️", "STORM drayn", "An opening in the street that carries rainwater to creeks and rivers without cleaning it, so only rain should go down it!", "Never dump anything down a storm drain.", "clean"],
  ["Backflow", "↩️", "BAK-floh", "When dirty water accidentally flows backward into clean water pipes. Special valves stop it.", "A backflow preventer keeps sprinkler water out of drinking water pipes.", "clean"],
  ["Water sample", "🧫", "WAH-ter SAM-pul", "A little bottle of water collected to test in a lab.", "The operator took a water sample to check for germs.", "clean"],
  ["Boil water notice", "📢", "BOYL WAH-ter NOH-tis", "A message telling people to boil their tap water before drinking it, because it might have germs.", "After the pipe broke, the town sent a boil water notice.", "clean"],
  ["Desalination", "🏝️", "dee-sal-uh-NAY-shun", "Taking the salt out of ocean water to make fresh water.", "Some dry places near the ocean use desalination to make drinking water.", "clean"],
  ["Hard water", "🫧", "HARD WAH-ter", "Water with lots of calcium and magnesium in it. It can leave white spots on dishes.", "Hard water makes it harder to get soap bubbles.", "clean"],

  /* ---------- Saving water ---------- */
  ["Conservation", "💚", "kon-ser-VAY-shun", "Protecting and saving natural resources, like using less water.", "Turning off the faucet while you brush is water conservation.", "save"],
  ["Leak", "💧", "LEEK", "A small hole or crack that lets water drip or run out.", "A faucet that drips once a second can waste over 3,000 gallons a year.", "save"],
  ["Rain barrel", "🛢️", "RAYN BAIR-ul", "A barrel that catches rainwater from a roof so it can water plants later.", "We used water from our rain barrel for the garden.", "save"],
  ["Irrigation", "🚜", "eer-uh-GAY-shun", "Watering crops and fields with pipes, sprinklers, or ditches.", "Farmers use irrigation when there isn't enough rain.", "save"],
  ["Drip irrigation", "🌱", "DRIP eer-uh-GAY-shun", "Watering plants with slow drips right at their roots, so less water is wasted.", "Drip irrigation keeps tomato plants happy with less water.", "save"],
  ["Low-flow", "🚿", "LOH-floh", "Showerheads, faucets, and toilets made to use less water.", "A low-flow showerhead saves water every time you shower.", "save"],
  ["Water footprint", "👣", "WAH-ter FOOT-print", "How much water it takes to make all the things you use, eat, and wear.", "It takes about 700 gallons of water to make one cotton T-shirt!", "save"],
  ["Natural resource", "🌳", "NACH-er-ul REE-sors", "Something from nature that people use, like water, trees, soil, and sunlight.", "Water is our most important natural resource.", "save"],
  ["Recycled water", "♻️", "ree-SY-kuld WAH-ter", "Used water that is cleaned so it can be used again, like for watering parks and golf courses.", "Some cities water their parks with recycled water.", "save"],
  ["Litter", "🥤", "LIT-er", "Trash left on the ground. Rain can wash it into creeks, rivers, and the ocean.", "Throwing trash in the can keeps litter out of the water.", "save"],
  ["Rain garden", "🌼", "RAYN GAR-den", "A garden planted in a low spot to catch rain from roofs and driveways so it soaks into the ground.", "A rain garden helps stop runoff and gives butterflies a home.", "save"],
  ["Xeriscaping", "🌵", "ZEER-uh-skay-ping", "Landscaping with plants that need very little water.", "Cactus and native grasses are great for xeriscaping.", "save"],
  ["World Water Day", "🌍", "WURLD WAH-ter DAY", "March 22 every year, a day to learn about fresh water and how to protect it.", "Our class made posters for World Water Day.", "save"]
];
