/* ==========================================================
   LearnWater — water operator glossary (Adult Learning Center)
   Definitions follow the Mississippi Waterworks Operators Manual
   and the lessons on this site; where a current federal rule
   differs, the definition says so.
   Each entry: [term, definition, chapters, also-known-as]
   (chapters are space-separated lesson ids; aliases are "|"-separated)
   Used by the Glossary tab, the lesson pages' key terms, and Greg.
   ========================================================== */
window.LW_GLOSSARY = [
  /* ---------- Chapter 1: Safe Drinking Water ---------- */
  ["Safe Drinking Water Act (SDWA)", "The federal law, passed in 1974 and amended in 1986 and 1996, that sets national standards for public drinking water. States with primacy enforce it; in Mississippi that is MSDH.", "ch1", "SDWA|safe drinking water act"],
  ["Primacy", "Primary enforcement authority for the Safe Drinking Water Act. EPA grants it to a state whose rules are at least as strict as the federal rules. Every state except Wyoming has primacy.", "ch1"],
  ["Mississippi State Department of Health (MSDH)", "The state agency with primacy for drinking water in Mississippi. Its Bureau of Public Water Supply regulates public water systems and certifies operators.", "ch1 ch2", "MSDH|state health department"],
  ["Bureau of Public Water Supply", "The MSDH office that runs Mississippi's drinking water program: compliance, sanitary surveys, operator certification, and backflow tester licensing. The manual calls it the Division of Water Supply.", "ch1 ch2", "division of water supply|DWS"],
  ["Public water system (PWS)", "A system that provides water for human consumption through pipes or other constructed conveyances to at least 15 service connections, or that regularly serves at least 25 people at least 60 days a year.", "ch1", "PWS|public water supply"],
  ["Community water system (CWS)", "A public water system that serves at least 15 service connections used by year-round residents, or regularly serves at least 25 year-round residents. Examples: towns, subdivisions, mobile home parks, and rural water associations.", "ch1", "CWS|community system"],
  ["Nontransient noncommunity water system (NTNCWS)", "A public water system that is not a community system but regularly serves at least 25 of the same people at least six months a year, such as a school, factory, or hospital with its own supply.", "ch1", "NTNC|NTNCWS|nontransient noncommunity"],
  ["Transient noncommunity water system (TNCWS)", "A public water system that serves people who change from day to day, such as a rest stop, restaurant, campground, or motel with its own well.", "ch1", "TNC|TNCWS|transient noncommunity"],
  ["Contaminant", "Any physical, chemical, biological, or radiological substance or matter in water.", "ch1"],
  ["Maximum contaminant level (MCL)", "The highest level of a contaminant allowed in water delivered to customers. MCLs are enforceable.", "ch1", "MCL"],
  ["Maximum contaminant level goal (MCLG)", "The level of a contaminant below which there is no known or expected risk to health. MCLGs are goals, not enforceable limits, and are set at zero for cancer-causing contaminants.", "ch1", "MCLG"],
  ["Maximum residual disinfectant level (MRDL)", "The highest level of a disinfectant allowed in drinking water: 4.0 mg/L for chlorine and for chloramines (as Cl₂), and 0.8 mg/L for chlorine dioxide.", "ch1 ch8d ch8a", "MRDL"],
  ["Treatment technique (TT)", "A required treatment process used instead of an MCL when a contaminant is hard or costly to measure. Examples: filtration and disinfection of surface water, and corrosion control for lead and copper.", "ch1", "TT"],
  ["Action level (AL)", "A concentration that triggers required steps when more than 10% of tap samples exceed it (the 90th percentile). Lead: 15 µg/L, dropping to 10 µg/L under the Lead and Copper Rule Improvements. Copper: 1.3 mg/L.", "ch1 ch7", "AL|lead action level|copper action level"],
  ["Primary drinking water standards", "Enforceable, health-based standards: MCLs, MRDLs, and treatment techniques.", "ch1", "primary standards|NPDWR|national primary drinking water regulations"],
  ["Secondary drinking water standards (SMCLs)", "Non-enforceable federal guidelines for aesthetic qualities such as taste, odor, color, and staining. Examples: iron 0.3 mg/L, manganese 0.05 mg/L, chloride 250 mg/L, TDS 500 mg/L.", "ch1 ch7", "secondary standards|SMCL"],
  ["Public notification (PN)", "Notice a water system must give its customers about violations and situations that may pose a risk to health. The current federal rule has three tiers based on urgency; the manual describes an older two-tier system.", "ch1", "PN|public notice"],
  ["Tier 1 public notice", "Notice for situations with an immediate risk to health, such as an E. coli MCL violation, a nitrate MCL violation, a waterborne disease outbreak, or (since October 2024) a lead action level exceedance. Due within 24 hours. In the manual's older system, Tier 1 meant any MCL or treatment technique violation.", "ch1", "tier 1|tier one"],
  ["Tier 2 public notice", "Notice for other MCL, MRDL, and treatment technique violations that are not immediate health risks. Due within 30 days and repeated every three months while the problem continues.", "ch1", "tier 2|tier two"],
  ["Tier 3 public notice", "Notice for monitoring and reporting violations and other minor issues. Due within one year; it can be included in the Consumer Confidence Report.", "ch1", "tier 3|tier three"],
  ["Consumer Confidence Report (CCR)", "The annual water quality report every community water system must deliver to customers by July 1, covering the previous calendar year. Delivery is certified to the state by October 1, and copies are kept at least three years.", "ch1", "CCR|water quality report|annual drinking water quality report"],
  ["Variance", "State permission for a system to exceed an MCL when it can't comply despite using the best available technology, as long as public health is protected. Variances are rare and come with conditions.", "ch1"],
  ["Exemption", "Temporary relief from an MCL or treatment technique for a system that needs more time (often to get financing) to comply, as long as there is no unreasonable risk to health.", "ch1"],
  ["Sanitary survey", "An on-site review of a water system's source, treatment, distribution, storage, pumps and controls, monitoring, management, and operator compliance, done to find deficiencies that could make water unsafe.", "ch1 ch5", "sanitary inspection"],
  ["Significant deficiency", "A defect found in a sanitary survey that could cause the delivery of unsafe water. Under the Ground Water Rule, the system consults the state within 30 days and must correct it, or be on a state-approved schedule, within 120 days.", "ch1 ch5"],
  ["Acute health effect", "Illness or other harm that shows up soon after exposure (hours or days), such as stomach illness from E. coli or blue baby syndrome from nitrate.", "ch1 ch6", "acute"],
  ["Chronic health effect", "Harm that develops after exposure over a long time, such as cancer or organ damage from drinking contaminated water for years.", "ch1", "chronic"],
  ["Emergency order", "An order EPA can issue when a contaminant presents an imminent and substantial danger to health. Violating one can bring fines of up to $25,000 per day, per violation.", "ch1"],
  ["Citizen suit", "A lawsuit a citizen can bring under the SDWA against a water system, the state, or EPA after giving 60 days' notice. Per the manual, class-action suits aren't allowed.", "ch1"],
  ["Ground Water Rule (GWR)", "A 2006 federal rule that protects ground water systems from fecal contamination through sanitary surveys, triggered source water monitoring, and corrective action for significant deficiencies.", "ch1 ch5", "GWR"],
  ["Lead and Copper Rule (LCR)", "The federal rule that controls lead and copper in tap water with action levels, corrosion control, tap sampling at high-risk homes, public education, and lead service line replacement.", "ch1 ch7", "LCR"],
  ["Lead and Copper Rule Improvements (LCRI)", "EPA's 2024 update to the Lead and Copper Rule. It lowers the lead action level to 10 µg/L and requires most lead service lines to be replaced within 10 years, with compliance starting November 1, 2027.", "ch1 ch9", "LCRI"],
  ["PFAS", "Per- and polyfluoroalkyl substances (\"forever chemicals\") from firefighting foam, coatings, and industry. EPA's 2024 rule set MCLs of 4.0 parts per trillion for PFOA and PFOS; in May 2026 EPA proposed more time to comply and dropping the other PFAS limits.", "ch1", "forever chemicals|PFOA|PFOS"],
  ["Unregulated contaminant", "A substance without an MCL that EPA may require systems to monitor, through the Unregulated Contaminant Monitoring Rule (UCMR), to decide whether it should be regulated.", "ch1", "UCMR"],
  ["Monitoring", "Collecting and analyzing water samples on a required schedule to show compliance with drinking water rules.", "ch1 ch6"],
  ["Compliance sample", "A sample collected to meet a regulatory monitoring requirement, as opposed to a sample taken only for process control.", "ch1 ch6"],
  ["Radionuclides", "Radioactive contaminants such as radium, uranium, and gross alpha emitters, regulated with MCLs under the Radionuclides Rule.", "ch1", "radium|uranium|gross alpha"],

  /* ---------- Chapter 2: Operator Certification ---------- */
  ["Certified operator", "A person certified by MSDH who directly supervises and is personally responsible for the daily operation and maintenance of a public water system. Every community and nontransient noncommunity system in Mississippi must have one.", "ch2", "certified waterworks operator|licensed operator|operator of record|responsible charge"],
  ["System classification", "The class (A, B, C, D, or E) MSDH assigns a water system based on the type of treatment it uses. The operator's certificate must be at least equal to the system's class.", "ch2", "classification"],
  ["Class A system", "A system that treats surface water, uses lime softening, or uses coagulation and filtration to remove constituents other than iron and manganese. The highest classification.", "ch2", "class a"],
  ["Class B system", "A system with two or more treatment facilities of different types, or with iron/manganese removal that breaks pressure or needs flocculation and/or sedimentation.", "ch2", "class b"],
  ["Class C system", "A system that uses aeration, pH adjustment, corrosion control, or closed-pressure treatment such as zeolite softening or iron removal.", "ch2", "class c"],
  ["Class D system", "A system with one or more wells and no treatment other than chlorination, fluoridation, and phosphate addition. The entry-level classification.", "ch2", "class d"],
  ["Class E", "The classification for systems that only purchase water, and for operators whose only job is running a distribution system.", "ch2", "class e"],
  ["Continuing education", "Approved training operators take to renew their certificates. Mississippi requires 48 hours in each three-year certificate period, or 24 hours for operators continuously licensed more than 9 years.", "ch2", "CEU|CEUs|continuing education units|CE hours"],
  ["Certificate renewal", "Mississippi operator certificates are good for three years. Renew by filing within 30 days after expiration with proof of the required continuing education, or you must pass the exam again.", "ch2", "license renewal|renewal"],
  ["Operators short course", "The four-day waterworks operators course offered before the certification exam, which is given three times a year.", "ch2", "short course"],
  ["Supervised experience", "Work under an operator holding an equal or higher certificate. At least one year is required for any Mississippi certification, and the supervisor must endorse the application.", "ch2", "experience requirement"],

  /* ---------- Chapter 3: Mathematics ---------- */
  ["Pure number", "A number with no units attached, such as 26 or 3/4.", "ch3"],
  ["Concrete number", "A number with units attached, such as 26 psi or 195 gallons. Convert concrete numbers to the same units before combining them.", "ch3"],
  ["Area", "The size of a flat surface, in square units such as ft². Rectangle: length × width. Circle: 0.785 × diameter².", "ch3"],
  ["Volume", "The space an object holds, in cubic units such as ft³. Rectangular tank: length × width × height. Cylinder: 0.785 × D² × height. Multiply ft³ by 7.48 for gallons.", "ch3"],
  ["Circumference", "The distance around a circle: π × diameter, about 3.14 × D.", "ch3", "perimeter of a circle"],
  ["Diameter", "The distance straight across a circle through its center; twice the radius.", "ch3"],
  ["Radius", "The distance from the center of a circle to its edge; half the diameter.", "ch3"],
  ["Pi (π)", "The ratio of a circle's circumference to its diameter, about 3.14. π ÷ 4 = 0.785, the factor in the circle-area formula 0.785 × D².", "ch3", "pi|0.785"],
  ["Ratio", "A comparison of two numbers, written X:Y or X/Y.", "ch3"],
  ["Proportion", "A statement that two ratios are equal. Cross-multiply to solve for an unknown.", "ch3"],
  ["Percent", "Parts per hundred. Move the decimal point two places left to turn a percent into a decimal (65% = 0.65).", "ch3", "percentage"],
  ["Average", "The sum of a set of values divided by how many values there are.", "ch3", "mean|arithmetic mean"],
  ["Exponent", "A small raised number showing how many times to multiply a number by itself: 2³ = 2 × 2 × 2 = 8.", "ch3", "squared|cubed|power"],
  ["Dimensional analysis", "Solving a problem by writing the units with every number and canceling them like fractions, so the answer ends up in the units you need.", "ch3", "unit cancellation|canceling units"],
  ["Conversion factor", "A number used to change a value from one unit to another, such as 7.48 gal/ft³, 8.34 lb/gal, or 2.31 ft/psi.", "ch3"],
  ["8.34 pounds per gallon", "The weight of one gallon of water. It's why 1 mg/L in one million gallons of water equals 8.34 pounds.", "ch3", "8.34|weight of water"],
  ["7.48 gallons per cubic foot", "The number of gallons in one cubic foot of water.", "ch3", "7.48"],
  ["Milligrams per liter (mg/L)", "The usual unit for concentrations in water. In drinking water, 1 mg/L is about the same as 1 part per million.", "ch3 ch7", "mg/L|mg/l|milligrams per liter"],
  ["Parts per million (ppm)", "One part of a substance per million parts of water, equal to about 1 mg/L in drinking water.", "ch3", "ppm"],
  ["Parts per billion (ppb)", "One part per billion, equal to about 1 µg/L. Lead and arsenic limits are written this way.", "ch3 ch7", "ppb|µg/L|micrograms per liter|ug/L"],
  ["Million gallons per day (MGD)", "A flow unit for plants and wells. 1 MGD = 694.4 gpm.", "ch3 ch4", "MGD|mgd"],
  ["Gallons per minute (gpm)", "A flow unit for pumps and wells. Multiply gpm by 1,440 to get gallons per day.", "ch3 ch4", "gpm"],
  ["Gallons per day (gpd)", "A flow unit used for daily demand and for basin overflow rates.", "ch3", "gpd"],
  ["Pounds formula", "lbs/day = dose (mg/L) × flow (MGD) × 8.34. Used for chlorine, alum, lime, and every other chemical feed calculation.", "ch3 ch8d", "pounds equation|lbs per day formula|lbs/day formula"],
  ["Dose", "The amount of chemical added to water, usually in mg/L. For chlorine, dose = demand + residual.", "ch3 ch8d", "dosage|chemical dose"],
  ["Feed rate", "How fast a chemical is added, usually in pounds per day or gallons per hour.", "ch3 ch8d"],
  ["Detention time", "How long water stays in a tank or basin: volume ÷ flow rate, with the time units matched.", "ch3 ch8bc", "retention time|hydraulic detention time|DT"],
  ["Specific gravity", "How heavy a substance is compared with water (water = 1.0). A liquid with a specific gravity of 1.2 weighs 1.2 × 8.34 = 10 pounds per gallon.", "ch3 ch8d", "SG"],
  ["Available chlorine", "The percentage of a product that works as chlorine: nearly 100% for chlorine gas, 65–70% for HTH, and about 5–15% for liquid sodium hypochlorite.", "ch3 ch8d", "purity|percent available chlorine"],

  /* ---------- Chapter 4: Hydraulics ---------- */
  ["Hydraulics", "The study of water at rest and in motion: pressure, head, flow, and pumping.", "ch4"],
  ["Head", "The height of a column of water, in feet, that represents energy or pressure. 1 foot of head = 0.433 psi.", "ch4", "feet of head"],
  ["Static head", "Head with no water moving: the vertical distance from the free water surface down to the point of measurement.", "ch4", "elevation head|static pressure"],
  ["Pressure head", "The part of total head that shows up as pressure at a point, in feet (psi × 2.31).", "ch4"],
  ["Velocity head", "The energy of water's movement, in feet (V² ÷ 2g). It's usually small in distribution systems.", "ch4"],
  ["Total dynamic head (TDH)", "The total head a pump works against: static lift plus friction losses plus any required discharge pressure (and velocity head).", "ch4", "TDH"],
  ["Friction loss", "Head lost as water rubs against pipe walls and passes valves and fittings. It rises with flow, pipe length, and roughness, and falls with bigger pipe.", "ch4", "head loss|friction head"],
  ["Hazen-Williams C factor", "A number describing how smooth a pipe is; higher is smoother. New PVC is about 150, new ductile iron about 130, and old tuberculated cast iron 50 or less.", "ch4", "C factor|C-factor|roughness coefficient"],
  ["Pounds per square inch (psi)", "The usual unit of water pressure. 1 psi = 2.31 feet of water; 1 foot of water = 0.433 psi.", "ch4", "psi|pressure"],
  ["Hydraulic grade line (HGL)", "A line showing how high water would rise in open tubes along a pipeline. It slopes down along the pipe by the amount of friction loss.", "ch4", "HGL"],
  ["Bernoulli's principle", "In flowing water, total head (elevation + pressure + velocity) stays constant except for losses, so where velocity goes up, pressure goes down.", "ch4", "bernoulli"],
  ["Flow rate (Q)", "The volume of water passing a point per unit of time, such as gpm or MGD. Q = A × V.", "ch4", "Q|flow"],
  ["Velocity", "How fast water moves, usually in feet per second. Distribution mains are designed to stay under 5 ft/sec.", "ch4", "ft/sec"],
  ["Venturi meter", "A flow meter with a narrowed throat; the pressure drop between the inlet and the throat tells the flow rate. The chlorinator ejector uses the same principle.", "ch4", "venturi"],
  ["Magnetic flow meter", "A meter with no moving parts that measures the voltage induced as water passes through a magnetic field.", "ch4", "mag meter|magmeter"],
  ["Displacement meter", "The common small residential meter; each turn of a disc or piston passes a fixed volume of water.", "ch4 ch9", "positive displacement meter|nutating disc meter"],
  ["Weir", "A wall or plate that water flows over. The height of water over it tells the flow; in a settling basin, it's the outlet edge.", "ch4 ch8bc"],
  ["Positive displacement pump", "A pump (piston, diaphragm, or rotary) that delivers a fixed volume per stroke or turn no matter the pressure. Used for chemical feed; never run it against a closed valve.", "ch4 ch8d", "PD pump|diaphragm pump|piston pump"],
  ["Centrifugal pump", "A pump that uses a spinning impeller to throw water outward and build pressure. It must be primed and has one best efficiency point on its curve.", "ch4"],
  ["Impeller", "The spinning, vaned part of a centrifugal pump that moves the water.", "ch4"],
  ["Volute", "The spiral casing of a centrifugal pump that collects water from the impeller and turns speed into pressure.", "ch4", "pump casing"],
  ["Priming", "Filling a pump casing and suction line with water before starting, so a centrifugal pump can move water.", "ch4", "prime"],
  ["Cavitation", "Vapor bubbles that form in a pump's low-pressure zones and collapse violently, causing a gravel-like noise, vibration, and pitting. Caused by too little suction pressure (NPSH).", "ch4"],
  ["Net positive suction head (NPSH)", "The pressure available at a pump's suction to keep water from flashing to vapor. If the available NPSH is less than the pump requires, it cavitates.", "ch4", "NPSH"],
  ["Shutoff head", "The head a centrifugal pump makes with the discharge closed and zero flow: the highest point on its curve.", "ch4", "shut-off head"],
  ["Pump curve", "The manufacturer's graph of a pump's head, efficiency, and power at each flow rate.", "ch4", "characteristic curve|performance curve"],
  ["Best efficiency point (BEP)", "The flow and head where a pump runs most efficiently. Operating near it saves power and wear.", "ch4", "BEP"],
  ["Affinity laws", "Rules for a centrifugal pump when its speed changes: flow changes with speed, head with speed squared, and power with speed cubed.", "ch4", "pump affinity laws"],
  ["Water hammer", "A pressure surge caused by suddenly stopping moving water, such as a fast-closing valve or a pump that trips. It can burst pipes, so close valves slowly.", "ch4 ch9", "surge|hydraulic shock|pressure surge"],
  ["Water horsepower (WHP)", "The power actually delivered to the water: gpm × TDH ÷ 3,960.", "ch4", "WHP"],
  ["Brake horsepower (BHP)", "The power the pump shaft needs: water horsepower ÷ pump efficiency.", "ch4", "BHP"],
  ["Motor horsepower (MHP)", "The power the motor draws: brake horsepower ÷ motor efficiency.", "ch4", "MHP"],
  ["Efficiency", "Useful output divided by input, as a percent. A pump that is 75% efficient turns 75% of its shaft power into water power.", "ch4"],
  ["Packing", "Rings of material around a pump shaft that seal where it leaves the casing. Packing should drip slightly to cool and lubricate the shaft.", "ch4", "pump packing|stuffing box"],
  ["Mechanical seal", "A shaft seal made of two polished faces pressed together; unlike packing, it should not drip.", "ch4"],
  ["Suction lift", "When the water source is below the pump's centerline, so the pump must lift water up to itself.", "ch4"],
  ["Pumps in series", "Pumps connected one after another. Their heads add at the same flow; used to reach higher pressure.", "ch4", "series pumping|series"],
  ["Pumps in parallel", "Pumps side by side feeding the same header. Their flows add at the same head; used to meet higher demand.", "ch4", "parallel pumping|parallel"],
  ["Variable frequency drive (VFD)", "A motor controller that changes pump speed to match demand, saving energy and softening starts and stops.", "ch4", "VFD|variable speed drive"],

  /* ---------- Chapter 5: Ground Water & Wells ---------- */
  ["Ground water", "Water beneath the surface in the saturated zone of soil and rock. About 88% of the water Mississippi public water systems use is ground water.", "ch5", "groundwater"],
  ["Aquifer", "An underground layer of sand, gravel, or rock that holds and transmits enough water to supply wells. Mississippi has 15 principal freshwater aquifers.", "ch5"],
  ["Confined aquifer", "An aquifer sealed above and below by impervious layers, so its water is under pressure.", "ch5"],
  ["Unconfined aquifer", "An aquifer with no impervious layer above it, so its top is the water table. Also called a water table aquifer, it's more exposed to surface contamination.", "ch5", "water table aquifer"],
  ["Artesian well", "A well in a confined aquifer where the water rises above the top of the aquifer. If it rises above ground and overflows the casing, it's a flowing artesian well.", "ch5", "flowing artesian well|artesian aquifer|artesian"],
  ["Water table", "The top of the saturated zone in an unconfined aquifer.", "ch5"],
  ["Zone of saturation", "The underground zone where all the spaces between soil and rock particles are filled with water.", "ch5", "saturated zone"],
  ["Zone of aeration", "The layer above the water table where the spaces hold both air and water.", "ch5", "unsaturated zone|vadose zone"],
  ["Recharge", "Water that soaks down to refill an aquifer, mostly from rain. A recharge area, often where the aquifer outcrops at the surface, is where this happens.", "ch5", "recharge area|outcrop"],
  ["Confining layer", "A layer of clay or rock that water moves through very slowly, sealing an aquifer from above or below.", "ch5", "aquitard|confining bed|impervious layer"],
  ["Porosity", "The percentage of a material's volume that is open space. High porosity doesn't guarantee high yield: clay is porous but gives up little water.", "ch5"],
  ["Permeability", "How easily water moves through a material, expressed in gallons per day per square foot.", "ch5"],
  ["Transmissivity", "The rate water flows through a vertical strip of an aquifer, in ft²/day. Mississippi aquifers range from about 5 to over 84,000 ft²/day.", "ch5"],
  ["Static water level", "The water level in a well when it isn't pumping, measured as depth below ground.", "ch5", "SWL|static level"],
  ["Pumping water level", "The water level in a well while it pumps, once the level has stabilized.", "ch5", "PWL|pumping level"],
  ["Drawdown", "The drop in a well's water level from the static level to the pumping level.", "ch5"],
  ["Cone of depression", "The funnel-shaped lowering of the water table or pressure surface around a pumping well.", "ch5", "cone of influence"],
  ["Radius of influence", "The distance from a pumping well to the edge of its cone of depression.", "ch5"],
  ["Specific capacity", "A well's yield per foot of drawdown: pumping rate (gpm) ÷ drawdown (ft). A steady drop over time can mean a clogging screen.", "ch5"],
  ["Well yield", "The volume of water a well can produce, usually in gpm.", "ch5", "yield|safe yield"],
  ["Well casing", "The pipe lining a drilled hole that keeps it from caving and keeps out water from the surface and other layers.", "ch5", "casing"],
  ["Grout", "Cement or clay sealing material placed in the space between a well casing and the borehole wall to block contamination and protect the casing.", "ch5", "grouting|annular seal"],
  ["Annular space", "The ring-shaped space between a well casing and the borehole wall, filled with grout.", "ch5", "annulus"],
  ["Well screen", "A slotted section at the bottom of a well that lets water in while holding back sand and gravel. Slot size is chosen from a sieve analysis.", "ch5", "screen"],
  ["Gravel pack", "Graded gravel placed around a well screen to hold back fine formation sand and improve flow.", "ch5", "filter pack"],
  ["Sieve analysis", "Sifting a sample of aquifer sand through a stack of screens to find its grain sizes, used to choose well screen slot size.", "ch5"],
  ["Well development", "Removing fine sand, silt, and drilling mud from around a new well screen by overpumping, surging, or jetting so the well produces at full capacity.", "ch5", "developing a well|surging"],
  ["Cable-tool drilling", "Drilling by repeatedly lifting and dropping a heavy bit; best in hard rock.", "ch5", "percussion drilling|cable tool"],
  ["Rotary drilling", "Drilling with a rotating bit and circulating drilling fluid (mud); best in unconsolidated sands and clays like Mississippi's.", "ch5", "hydraulic rotary|rotary"],
  ["Sanitary seal", "A watertight well cap or seal at the top of the casing that keeps out insects, surface water, and contaminants.", "ch5", "well cap|sanitary well cap"],
  ["Wellhead protection", "Managing land use around a well and its recharge area to keep contaminants out of the water supply.", "ch5", "source water protection|wellhead protection area|source water assessment"],
  ["Well abandonment", "Permanently sealing an unused well with grout so it can't become a direct path for contamination to reach the aquifer.", "ch5", "plugging a well|abandoned well"],
  ["Encrustation", "Mineral scale, often iron, manganese, or calcium carbonate, that clogs well screens and reduces yield.", "ch5"],
  ["Iron bacteria", "Bacteria that feed on dissolved iron and form slimy deposits that clog wells and cause red water and odors.", "ch5 ch7", "biofouling"],
  ["Well rehabilitation", "Restoring a well's yield by chemical treatment (acid for scale, chlorine for bacteria) combined with mechanical surging or brushing, then redevelopment and disinfection.", "ch5", "well rehab"],
  ["Downdip limit", "The point, deeper in an aquifer, where dissolved solids pass about 1,000 mg/L and the water is no longer considered fresh.", "ch5"],

  /* ---------- Chapter 6: Microbiology ---------- */
  ["Microorganism", "A living thing too small to see without a microscope, such as bacteria, viruses, and protozoa.", "ch6", "microbe|micro-organism"],
  ["Pathogen", "A microorganism that causes disease.", "ch6", "disease-causing organism|pathogens"],
  ["Bacteria", "Single-celled microorganisms that reproduce by splitting in two (binary fission), as often as every 20–30 minutes in good conditions.", "ch6", "bacterium|binary fission"],
  ["Virus", "A tiny infectious particle, far smaller than bacteria, that can reproduce only inside a host cell. Enteric viruses need longer chlorine contact time than bacteria.", "ch6", "viruses"],
  ["Protozoa", "Single-celled organisms, such as Giardia and Cryptosporidium, whose cysts and oocysts resist chlorine.", "ch6", "protozoan"],
  ["Cyst", "A tough resting form of a protozoan, like Giardia, that survives for months and resists disinfectants. Cryptosporidium's version is called an oocyst.", "ch6", "oocyst|oocysts|cysts"],
  ["Giardia lamblia", "A protozoan that causes giardiasis (diarrhea and cramps). Its cysts are removed by filtration and inactivated by adequate chlorine CT.", "ch6 ch8a", "giardia"],
  ["Cryptosporidium", "A protozoan whose oocysts strongly resist chlorine and are small enough to pass some filters. It takes multiple barriers: coagulation, filtration, and UV or ozone.", "ch6 ch8a", "crypto"],
  ["Total coliform", "A group of bacteria used as an indicator: finding them means contamination may have entered the water. Most are not harmful themselves.", "ch6", "coliform|coliform bacteria|TC"],
  ["Fecal coliform", "Coliform bacteria from the intestines of warm-blooded animals; a more specific sign of fecal contamination than total coliform.", "ch6", "thermotolerant coliform"],
  ["E. coli", "Escherichia coli, a fecal coliform that is the best indicator of recent fecal contamination. An E. coli MCL violation is an acute (Tier 1) health risk.", "ch6", "Escherichia coli|e coli|ecoli"],
  ["Indicator organism", "An organism that signals possible contamination with pathogens. Coliforms are used because they're present whenever sewage is, easy to test for, and outlive most pathogens.", "ch6", "indicator"],
  ["Heterotrophic plate count (HPC)", "A lab count of general bacteria in water, used to judge treatment and distribution conditions, not as a sign of sewage.", "ch6", "HPC|standard plate count"],
  ["Colilert", "An enzyme-substrate test for total coliform and E. coli: the sample turns yellow for coliform and glows blue under UV light for E. coli. The MSDH lab uses it.", "ch6", "enzyme substrate test"],
  ["Routine sample", "A regularly scheduled compliance sample collected from sites in the sample siting plan.", "ch6"],
  ["Repeat sample", "A follow-up after a total-coliform-positive routine sample. Under the RTCR, take at least three within 24 hours: at the original tap and within five connections upstream and downstream. The manual calls these check samples.", "ch6", "check sample|repeat samples"],
  ["Sample siting plan", "The state-approved list of sampling sites that represent the whole distribution system. The manual requires at least five sites.", "ch6", "sampling plan|sample sites"],
  ["Sodium thiosulfate", "A chemical in bacteriological sample bottles that neutralizes chlorine so it stops killing bacteria before the lab tests the sample.", "ch6", "thiosulfate"],
  ["Revised Total Coliform Rule (RTCR)", "The federal coliform rule since April 1, 2016. It sets an E. coli MCL, requires repeat samples after a positive, and requires Level 1 or Level 2 assessments to find and fix causes.", "ch6", "RTCR|total coliform rule|TCR"],
  ["Level 1 assessment", "A self-assessment required under the RTCR when coliform results suggest a problem, such as two or more total-coliform-positive samples in a month for a system taking fewer than 40 samples.", "ch6", "level one assessment"],
  ["Level 2 assessment", "A more detailed assessment by the state or a state-approved party, triggered by an E. coli MCL violation or a second Level 1 trigger within 12 months.", "ch6", "level two assessment"],
  ["Log removal", "A way to express treatment effectiveness: 1-log = 90% removed or inactivated, 2-log = 99%, 3-log = 99.9%, 4-log = 99.99%.", "ch6 ch8a", "log reduction|log inactivation|log"],
  ["Inactivation", "Making a microorganism unable to reproduce or cause infection, usually by disinfection.", "ch6"],
  ["Waterborne disease outbreak", "Illness in two or more people linked to drinking water. It requires Tier 1 public notice.", "ch6", "outbreak"],
  ["Aerobic", "Needing oxygen to live. Anaerobic organisms live without oxygen; facultative ones can do either.", "ch6", "anaerobic|facultative"],
  ["Bacillus", "A rod-shaped bacterium; over 80% of bacteria are this shape. Round bacteria are cocci and spiral ones are spirilla.", "ch6", "rod-shaped|coccus|cocci|spirillum"],
  ["Enteric", "Of the intestines. Enteric bacteria and viruses spread through fecal contamination.", "ch6"],
  ["Legionella", "A bacterium that grows in warm water systems and can cause Legionnaires' disease when people breathe in contaminated mist.", "ch6 ch8a", "legionnaires"],

  /* ---------- Chapter 7: Chemistry ---------- */
  ["Ion", "An atom or group of atoms with an electric charge. Positive ions are cations (like Ca²⁺); negative ions are anions (like HCO₃⁻).", "ch7", "cation|anion|ions"],
  ["pH", "A 0–14 scale of hydrogen ion activity. 7 is neutral; lower is acidic and higher is basic. Each whole number is a tenfold change.", "ch7", "ph"],
  ["Acid", "A substance that releases hydrogen ions and lowers pH, such as sulfuric acid, alum, and carbon dioxide dissolved in water.", "ch7", "acidic"],
  ["Base", "A substance that raises pH, such as lime, soda ash, and caustic soda. Basic water is also called alkaline.", "ch7", "alkaline|basic|caustic"],
  ["Alkalinity", "Water's ability to neutralize acid, mostly from bicarbonate, carbonate, and hydroxide ions. It's measured as mg/L CaCO₃ and is needed for coagulation.", "ch7"],
  ["Bicarbonate", "The ion HCO₃⁻, which provides most of the alkalinity in natural water.", "ch7", "HCO3"],
  ["Hardness", "The concentration of calcium and magnesium (and a few other metals) in water, as mg/L CaCO₃. Soft is under 75; moderate 75–150; hard 150–200; very hard over 200.", "ch7", "water hardness|total hardness"],
  ["Carbonate hardness", "Hardness that can be removed by heating (\"temporary\" hardness). It equals the alkalinity or the total hardness, whichever is less.", "ch7", "temporary hardness"],
  ["Noncarbonate hardness", "Hardness left after the carbonate hardness is accounted for; heating doesn't remove it (\"permanent\" hardness).", "ch7", "permanent hardness|non-carbonate hardness"],
  ["Calcium carbonate (CaCO₃)", "The compound hardness and alkalinity are expressed as, and the scale that forms in pipes and heaters.", "ch7", "CaCO3|limestone"],
  ["Grains per gallon (gpg)", "An older hardness unit used on home softeners: 1 grain per gallon = 17.1 mg/L.", "ch7", "gpg|grains"],
  ["Total dissolved solids (TDS)", "All the minerals and other substances dissolved in water, in mg/L. The secondary standard is 500 mg/L.", "ch7 ch5", "TDS|dissolved solids"],
  ["Solution", "A mixture in which a substance (the solute) is dissolved evenly in a liquid (the solvent), so every part is exactly the same.", "ch7", "solute|solvent"],
  ["Precipitate", "A solid that forms in water from dissolved substances, such as rust particles from iron or calcium carbonate in softening.", "ch7 ch8bc", "precipitation (chemistry)"],
  ["Oxidation", "A reaction where a substance loses electrons. In treatment, oxidants (air, chlorine, permanganate) turn dissolved iron and manganese into solids that can be filtered.", "ch7 ch8bc", "oxidize|oxidizing agent|oxidant"],
  ["Reduction", "A reaction where a substance gains electrons; the opposite of oxidation.", "ch7"],
  ["Buffer", "A solution that resists changes in pH. Alkalinity is what buffers natural water.", "ch7", "buffering"],
  ["Titration", "A lab method that adds a reagent drop by drop until a color change marks the end point; used for alkalinity and hardness tests.", "ch7", "titrate"],
  ["Iron", "A common metal in ground water. Above 0.3 mg/L it stains fixtures and laundry reddish-brown and gives a metallic taste.", "ch7 ch8bc", "Fe|red water"],
  ["Manganese", "A metal in ground water that causes black stains above 0.05 mg/L. It's harder to oxidize than iron.", "ch7 ch8bc", "Mn|black water"],
  ["Hydrogen sulfide (H₂S)", "A gas that gives water a rotten-egg odor. It's toxic in enclosed spaces and uses up chlorine (per the manual, 1 mg/L of H₂S uses about 2.1 mg/L of chlorine).", "ch7 ch8d", "H2S|rotten egg odor|sulfur smell"],
  ["Carbon dioxide (CO₂)", "A gas that dissolves in water to form carbonic acid, lowering pH. Aeration removes it; softening plants add it back in recarbonation.", "ch7 ch8bc", "CO2"],
  ["Nitrate", "A form of nitrogen from fertilizer, septic systems, and animal waste. The MCL is 10 mg/L (as nitrogen) because it causes blue baby syndrome in infants.", "ch7", "NO3|blue baby syndrome|methemoglobinemia"],
  ["Arsenic", "A toxic element found naturally in some ground water. The MCL is 10 µg/L (0.010 mg/L).", "ch7"],
  ["Turbidity", "Cloudiness caused by suspended particles, measured in NTU. It can shield microorganisms from disinfection.", "ch7 ch8bc ch8a", "cloudiness|cloudy water"],
  ["Nephelometric turbidity unit (NTU)", "The unit for turbidity, measured by how much light the particles scatter.", "ch7 ch8bc", "NTU"],
  ["Color", "Tint in water from dissolved organic matter (tea-colored) or from metals like iron and manganese.", "ch7", "true color"],
  ["Corrosion", "The gradual wearing away of pipe and fixture metal by water. Corrosive water raises lead and copper levels and causes leaks.", "ch7 ch8bc", "corrosive water"],
  ["Scale", "Hard mineral deposits, usually calcium carbonate, that form inside pipes, heaters, and filters.", "ch7 ch8bc", "scaling"],
  ["Element", "A pure substance made of one kind of atom, such as oxygen or iron.", "ch7"],
  ["Compound", "A substance made of two or more elements chemically combined, such as water (H₂O) or calcium carbonate.", "ch7"],
  ["Molecule", "The smallest unit of a compound that keeps its properties, such as one H₂O.", "ch7"],

  /* ---------- Chapter 8 (D): Class D treatment ---------- */
  ["Disinfection", "Killing or inactivating disease-causing organisms in water. Unlike sterilization, it doesn't kill every organism.", "ch8d", "disinfect"],
  ["Chlorination", "Adding chlorine to water for disinfection and oxidation.", "ch8d", "chlorinate"],
  ["Chlorine demand", "The chlorine used up reacting with iron, manganese, hydrogen sulfide, organic matter, and other substances before a residual forms. Demand = dose − residual.", "ch8d", "demand"],
  ["Chlorine residual", "Chlorine remaining in water after the demand is met and contact time has passed. Keep at least 0.2 mg/L free chlorine throughout the distribution system.", "ch8d", "residual"],
  ["Free chlorine residual", "Chlorine present as hypochlorous acid and hypochlorite ion; the strongest, fastest-acting residual.", "ch8d", "free residual|free available chlorine|free chlorine"],
  ["Combined chlorine residual", "Chlorine combined with ammonia as chloramines. It lasts longer but disinfects much more slowly than free chlorine.", "ch8d", "combined residual|combined chlorine"],
  ["Total chlorine residual", "Free plus combined chlorine residual.", "ch8d", "total residual|total chlorine"],
  ["Chloramines", "Compounds of chlorine and ammonia. Some systems use them on purpose for a long-lasting residual with fewer byproducts.", "ch8d ch8a", "monochloramine|chloramine"],
  ["Breakpoint chlorination", "Adding enough chlorine to destroy the chloramines (the breakpoint), so any more chlorine shows up as free residual.", "ch8d", "breakpoint|chlorination curve|chlorine curve"],
  ["Hypochlorous acid (HOCl)", "The strongest form of free chlorine. It dominates at lower pH, which is why chlorine works better at lower pH.", "ch8d", "HOCl"],
  ["Hypochlorite ion (OCl⁻)", "The weaker form of free chlorine, which dominates at higher pH.", "ch8d", "OCl"],
  ["Contact time", "How long disinfectant is in contact with water before the first customer. The manual recommends 15–30 minutes for chlorine.", "ch8d", "chlorine contact time"],
  ["CT value", "Disinfectant residual (mg/L) × contact time (minutes). Rules require enough CT to inactivate Giardia and viruses.", "ch8d ch8a", "CT|C x T|C times T"],
  ["Calcium hypochlorite (HTH)", "A dry granular or tablet chlorine with about 65–70% available chlorine. Keep it away from oil and organic material; it can start fires.", "ch8d ch10", "HTH|high test hypochlorite|cal hypo"],
  ["Sodium hypochlorite", "Liquid chlorine bleach, about 5–15% available chlorine. It loses strength with heat, sunlight, and time.", "ch8d ch10", "bleach|hypo|liquid bleach"],
  ["Hypochlorinator", "A chemical feed pump, usually positive displacement, that feeds hypochlorite solution into a water line.", "ch8d", "chlorine feed pump"],
  ["Chemical metering pump", "A small positive displacement pump that feeds an exact, adjustable amount of chemical solution.", "ch8d", "metering pump|feed pump"],
  ["DPD test", "The standard field test for chlorine residual: DPD reagent turns pink in proportion to the chlorine. Use DPD free reagent for free chlorine and DPD total reagent for total chlorine.", "ch8d", "DPD|chlorine test kit|colorimeter"],
  ["Fluoridation", "Adjusting the fluoride in drinking water to help prevent tooth decay. The manual lists 0.8–1.2 mg/L; the U.S. Public Health Service has recommended 0.7 mg/L since 2015.", "ch8d", "fluoride"],
  ["Sodium fluoride (NaF)", "A white salt used for fluoridation, usually fed as a saturated (about 4%) solution from a saturator.", "ch8d", "NaF"],
  ["Fluorosilicic acid", "A corrosive liquid (about 22–30%) used for fluoridation. The manual calls it hydrofluosilicic acid (H₂SiF₆).", "ch8d", "hydrofluosilicic acid|H2SiF6|FSA"],
  ["Sodium silicofluoride", "A dry crystalline powder (Na₂SiF₆) used for fluoridation, usually fed with a dry feeder at larger plants.", "ch8d", "sodium fluorosilicate|Na2SiF6"],
  ["Saturator", "A tank where water flows up through a bed of sodium fluoride crystals, making a saturated solution (about 18,000 mg/L fluoride) that is then metered into the water.", "ch8d", "fluoride saturator"],
  ["Dental fluorosis", "White spots or mottling on children's teeth from too much fluoride while teeth are forming. The secondary standard for fluoride (2.0 mg/L) protects against it.", "ch8d", "fluorosis"],
  ["Orthophosphate", "A phosphate chemical that forms a protective film inside pipes to reduce lead and copper corrosion.", "ch8d ch7", "phosphate|corrosion inhibitor"],
  ["Polyphosphate", "A phosphate chemical that keeps iron and manganese dissolved (sequestered) so they don't stain.", "ch8d", "sequestering agent"],
  ["Sequestering", "Tying up dissolved iron or manganese with a chemical such as polyphosphate so it stays in solution and doesn't oxidize and stain.", "ch8d ch8bc", "sequestration"],

  /* ---------- Chapter 8 (B&C): Unit processes ---------- */
  ["Aeration", "Mixing air into water to remove gases (carbon dioxide, hydrogen sulfide, methane), oxidize iron and manganese, and add oxygen.", "ch8bc", "aerate"],
  ["Tray aerator", "An aerator where water trickles down through stacked trays of coke, stone, or slats, often with a fan forcing air through.", "ch8bc", "cascade aerator|forced draft aerator|aerator"],
  ["Coagulation", "Rapidly mixing a positively charged coagulant into water to neutralize the negative charges on particles so they can clump. It happens in 1–2 seconds.", "ch8bc ch7", "coagulant"],
  ["Flocculation", "Gentle, slow mixing after coagulation that lets small particles collide and grow into larger floc that can settle.", "ch8bc", "flocculator"],
  ["Floc", "The clumps of particles formed during coagulation and flocculation.", "ch8bc ch7"],
  ["Rapid mix", "Fast, violent mixing that spreads the coagulant through the water instantly.", "ch8bc", "flash mix"],
  ["Zeta potential", "The electrical charge on particles in water, usually negative, that makes them repel each other. Coagulants neutralize it.", "ch8bc"],
  ["Alum", "Aluminum sulfate, the most common coagulant. It reacts with alkalinity to form aluminum hydroxide floc.", "ch8bc ch7", "aluminum sulfate"],
  ["Ferric coagulants", "Iron-based coagulants such as ferric chloride and ferric sulfate, which work over a wider pH range than alum.", "ch8bc", "ferric sulfate|ferric chloride|iron salts"],
  ["Polymer", "A long-chain chemical used as a coagulant or coagulant aid to build stronger floc and help filtration.", "ch8bc ch8a", "polyelectrolyte"],
  ["Sedimentation", "Letting water sit quietly in a basin so heavy floc and particles settle out.", "ch8bc", "settling"],
  ["Clarifier", "A sedimentation basin; some combine flocculation and settling in one unit (a solids contact clarifier).", "ch8bc", "settling basin|sedimentation basin"],
  ["Surface overflow rate", "Flow divided by basin surface area, in gpd/ft². A typical rate for alum floc is about 500 gpd/ft².", "ch8bc", "overflow rate|surface loading rate"],
  ["Weir overflow rate", "Flow divided by the length of the outlet weir, in gpd/ft. The manual's limit is 20,000 gpd per foot.", "ch8bc", "weir loading rate"],
  ["Short-circuiting", "Water taking a faster path through a basin than the design detention time, usually from poor inlet baffling or density currents. It hurts settling.", "ch8bc ch8a", "short circuiting"],
  ["Sludge", "The settled solids removed from basins, plus the solids washed out of filters.", "ch8bc", "residuals"],
  ["Filtration", "Passing water through sand, anthracite, or other media to remove particles, floc, and microorganisms.", "ch8bc", "filter"],
  ["Rapid sand filter", "A gravity filter of sand (or sand and anthracite) run at about 2 gpm/ft² for single media and 3 gpm/ft² for dual media, and cleaned by backwashing.", "ch8bc", "gravity filter"],
  ["Dual-media filter", "A filter with a layer of coarse, light anthracite over fine, heavy sand, so particles are captured through more of the bed.", "ch8bc", "dual media|multimedia filter"],
  ["Anthracite", "Hard coal used as the top layer in dual-media filters.", "ch8bc"],
  ["Filter loading rate", "Flow divided by filter surface area, in gpm/ft².", "ch8bc", "filtration rate|filter rate"],
  ["Filter head loss", "The pressure lost as water passes through a filter bed. It rises as the filter collects dirt; backwash at 7–10 feet.", "ch8bc", "head loss (filter)"],
  ["Backwash", "Reversing flow up through a filter to lift and clean the media: 15–20 gpm/ft² for sand, 10–15 gpm/ft² for dual media, until the wash water runs clear.", "ch8bc", "backwashing|backwash rate"],
  ["Bed expansion", "How much a filter bed lifts during backwash, as a percent of its depth; typically 20–50%.", "ch8bc"],
  ["Surface wash", "Water jets or rotating arms that scrub the top of a filter bed during backwash to break up mudballs.", "ch8bc"],
  ["Filter-to-waste", "Sending the first water through a freshly backwashed filter to waste until turbidity drops.", "ch8bc", "filter to waste|rewash"],
  ["Mudball", "A clump of media and dirt that forms in a filter that isn't backwashed well enough.", "ch8bc", "mudballs"],
  ["Breakthrough", "When particles start passing through a filter and effluent turbidity rises, signaling the end of the run.", "ch8bc", "turbidity breakthrough"],
  ["Turbidimeter", "An instrument that measures turbidity in NTU from the light scattered by particles.", "ch8bc", "nephelometer"],
  ["Pressure filter", "A filter inside a closed steel tank that works under system pressure, common for iron removal at small well systems.", "ch8bc", "pressure filters"],
  ["Greensand", "Filter media coated with manganese oxide that removes iron and manganese; it's regenerated with potassium permanganate.", "ch8bc", "manganese greensand"],
  ["Potassium permanganate (KMnO₄)", "A purple oxidant that removes iron and manganese (faster than chlorine, from pH 5 to 9) and controls taste and odor. Pink water means an overfeed.", "ch8bc ch8a", "KMnO4|permanganate"],
  ["Ion exchange", "Passing water through resin that swaps one ion for another, usually sodium for calcium and magnesium (softening). Best under 2,000 mg/L TDS.", "ch8bc", "ion exchange softening"],
  ["Zeolite", "A mineral or synthetic material used as ion exchange media in water softeners.", "ch8bc"],
  ["Regeneration", "Restoring spent ion exchange resin with a strong salt brine (20–35 minutes of contact).", "ch8bc", "brining|regenerate"],
  ["Softening", "Removing hardness (calcium and magnesium), either by ion exchange or by lime-soda ash precipitation.", "ch8bc ch8a", "water softening|softener"],
  ["Stabilization", "Adjusting water so it's neither corrosive nor scale-forming.", "ch8bc", "water stability"],
  ["Langelier Saturation Index (LSI)", "A number that predicts whether water will deposit or dissolve calcium carbonate: slightly positive lays down a protective scale; negative is corrosive. Valid from pH 6.5 to 9.5.", "ch8bc", "LSI|Langelier index|saturation index"],

  /* ---------- Chapter 8 (A): Surface water ---------- */
  ["Surface water", "Water in rivers, lakes, streams, and reservoirs. About 10% of Mississippians drink it, compared with about 75% nationally.", "ch8a"],
  ["Raw water", "Untreated water from the source.", "ch8a ch8bc"],
  ["Intake", "The structure that draws raw water from a river or lake, usually through screens.", "ch8a"],
  ["Screening", "Using bar screens and fine mesh to remove sticks, leaves, fish, and trash before water enters the plant.", "ch8a", "bar screen"],
  ["Presedimentation", "Settling raw water before the main treatment to remove heavy silt and even out quality swings; useful on rivers.", "ch8a", "pre-sedimentation|presed"],
  ["Coagulant aid", "A chemical added along with the coagulant, such as activated silica, bentonite clay, or a polymer, to build stronger, faster-settling floc.", "ch8a", "activated silica|bentonite"],
  ["Streaming current monitor", "An instrument that measures particle charge after the coagulant is added, to help keep the dose right as raw water changes.", "ch8a", "streaming current detector|SCD"],
  ["Algae", "Simple plant-like organisms in surface water that can clog filters, cause taste and odor, and raise pH and chlorine demand.", "ch8a"],
  ["Algal bloom", "A rapid growth of algae, often in warm, nutrient-rich water. Some blooms of cyanobacteria (blue-green algae) make toxins.", "ch8a", "harmful algal bloom|HAB|blue-green algae|cyanobacteria"],
  ["Geosmin", "An earthy-smelling compound made by some algae and bacteria. People can smell it, and the similar musty compound MIB, at a few parts per trillion.", "ch8a", "MIB|2-methylisoborneol|earthy taste|musty taste"],
  ["Taste and odor", "Complaints like earthy, musty, fishy, or chlorine tastes; often from algae or iron and controlled with activated carbon, oxidants, and good treatment.", "ch8a", "T&O|taste and odor control"],
  ["Powdered activated carbon (PAC)", "Fine carbon added to water to adsorb taste and odor compounds and some organics; it's removed by settling and filtration.", "ch8a", "PAC"],
  ["Granular activated carbon (GAC)", "Carbon grains used as filter media or in contactors to adsorb organics, tastes, and odors.", "ch8a", "GAC|activated carbon"],
  ["Adsorption", "Molecules sticking to a surface, such as organics sticking to activated carbon.", "ch8a"],
  ["Lime-soda ash softening", "Adding lime (and soda ash for noncarbonate hardness) to precipitate calcium carbonate near pH 9.4 and magnesium hydroxide near pH 10.6. It leaves 50–80 mg/L of hardness on purpose.", "ch8a", "lime softening|lime-soda softening"],
  ["Recarbonation", "Adding carbon dioxide after lime softening to lower the pH, to about 8.6, and stop scale from forming in filters and mains.", "ch8a"],
  ["Disinfection byproducts (DBPs)", "Compounds formed when disinfectants react with natural organic matter, such as trihalomethanes and haloacetic acids.", "ch8a", "DBP|DBPs|byproducts"],
  ["Total trihalomethanes (TTHM)", "A group of four disinfection byproducts; chloroform is the most common. MCL: 0.080 mg/L as a locational running annual average.", "ch8a", "TTHM|THM|THMs|trihalomethanes|chloroform"],
  ["Haloacetic acids (HAA5)", "A group of five disinfection byproducts. MCL: 0.060 mg/L as a locational running annual average.", "ch8a", "HAA5|haloacetic acids"],
  ["Locational running annual average (LRAA)", "The average of the last four quarterly results at one monitoring location, used for Stage 2 DBP compliance.", "ch8a", "LRAA"],
  ["Natural organic matter (NOM)", "Decayed plant and animal material in water that adds color and reacts with chlorine to form byproducts.", "ch8a", "NOM|DBP precursors|precursors"],
  ["Total organic carbon (TOC)", "A measure of the organic matter in water, used to judge how much byproduct it can form. Conventional surface water plants must remove a set percentage.", "ch8a", "TOC"],
  ["Enhanced coagulation", "Adjusting coagulant dose and pH to remove more organic matter (TOC) and cut byproduct formation.", "ch8a"],
  ["Chlorine dioxide (ClO₂)", "A strong oxidant and disinfectant generated on site. It forms no THMs but produces chlorite. MRDL 0.8 mg/L; chlorite MCL 1.0 mg/L.", "ch8a", "ClO2|chlorite"],
  ["Ozone (O₃)", "A very strong disinfectant generated on site from oxygen. It leaves no residual and can form bromate if bromide is present.", "ch8a", "ozone|O3|ozonation"],
  ["Bromate", "A disinfection byproduct formed when ozone reacts with bromide. MCL: 0.010 mg/L.", "ch8a"],
  ["Ultraviolet (UV) disinfection", "Using UV light to inactivate microorganisms. It's very effective against Cryptosporidium and Giardia but leaves no residual.", "ch8a", "UV|ultraviolet"],
  ["Membrane filtration", "Forcing water through thin membranes to remove particles and microbes (microfiltration, ultrafiltration) or dissolved salts (nanofiltration, reverse osmosis).", "ch8a", "membranes|microfiltration|ultrafiltration|nanofiltration"],
  ["Reverse osmosis (RO)", "A membrane process that pushes water through a very tight membrane under pressure, removing dissolved salts; used for desalination.", "ch8a", "RO|desalination"],
  ["Surface Water Treatment Rule (SWTR)", "The federal rules requiring systems that use surface water (or ground water under its influence) to filter and disinfect for at least 3-log Giardia and 4-log virus removal or inactivation.", "ch8a", "SWTR|surface water treatment rules|IESWTR|LT1ESWTR"],
  ["LT2ESWTR", "The Long Term 2 Enhanced Surface Water Treatment Rule, which uses source water Cryptosporidium monitoring to place systems in bins that may require added treatment.", "ch8a", "LT2|long term 2"],
  ["Combined filter effluent (CFE)", "Water from all filters combined. At conventional and direct filtration plants, CFE turbidity must be 0.3 NTU or less in 95% of monthly readings and never above 1 NTU.", "ch8a ch8bc", "CFE"],
  ["Individual filter effluent (IFE)", "Turbidity from each filter, monitored continuously and recorded every 15 minutes at conventional and direct filtration plants.", "ch8a ch8bc", "IFE|individual filter turbidity"],
  ["Ground water under the direct influence of surface water (GWUDI)", "Ground water, such as from a shallow well or spring, that surface water affects quickly enough that it must be treated like surface water.", "ch8a ch5", "GWUDI|GUDI"],

  /* ---------- Chapter 9: Distribution & Storage ---------- */
  ["Distribution system", "All the pipes, valves, hydrants, storage tanks, pumps, and meters that carry treated water from the plant or well to customers.", "ch9", "distribution"],
  ["Water main", "A distribution pipe that serves many customers. The recommended minimum is 4 inches, or 6 inches where it supplies fire hydrants.", "ch9", "main|mains"],
  ["Service line", "The pipe from the water main to a customer's building.", "ch9", "service connection|service pipe"],
  ["Looped system", "A layout where mains connect in loops so water can reach a point from more than one direction, keeping water fresher and pressure steadier.", "ch9", "grid system|looping"],
  ["Dead end", "A main with no connection at the far end. Water there sits, loses chlorine, and needs flushing.", "ch9", "dead-end main"],
  ["Gate valve", "A valve with a gate that slides across the flow, used fully open or fully closed to isolate sections of main.", "ch9"],
  ["Butterfly valve", "A valve with a disc that turns a quarter turn to open or close; common on large mains and in plants.", "ch9"],
  ["Check valve", "A valve that lets water flow one way only and closes when flow reverses.", "ch9 ch12"],
  ["Air-release valve", "A valve at a high point that lets trapped air escape from a pressurized main.", "ch9", "air relief valve|air/vacuum valve|combination air valve"],
  ["Pressure-reducing valve (PRV)", "A valve that lowers high incoming pressure to a steady, safe outlet pressure. Inspect PRVs monthly.", "ch9", "PRV|pressure regulating valve"],
  ["Altitude valve", "A valve that shuts off flow into an elevated tank or standpipe at a set level to prevent overflow.", "ch9"],
  ["Fire hydrant", "A firefighting outlet on the distribution system, also used for flushing and flow testing. The manual calls for hydrant maintenance twice a year.", "ch9", "hydrant|hydrants"],
  ["Dry-barrel hydrant", "A hydrant whose main valve sits below the frost line, so the barrel drains when it's closed.", "ch9", "dry barrel"],
  ["Hydrant color code", "The NFPA 291 bonnet colors that show available flow at 20 psi: light blue 1,500 gpm or more, green 1,000–1,499, orange 500–999, red under 500.", "ch9", "hydrant colors|hydrant bonnet color|NFPA 291"],
  ["Flushing", "Opening hydrants or blowoffs to move water fast enough to scour sediment, remove stale water, and restore chlorine residual.", "ch9", "main flushing|hydrant flushing"],
  ["Unidirectional flushing", "Flushing mains in a planned sequence, closing valves so water moves one way at high velocity (ideally around 5 ft/sec), from clean pipe into dirty pipe.", "ch9", "UDF|unidirectional"],
  ["Blowoff", "A valve and outlet at a low point or dead end used to drain or flush a main.", "ch9", "blow-off"],
  ["Hydrostatic test", "A pressure test of new main at 1.5 times normal operating pressure, held at least an hour, checking for leaks.", "ch9", "pressure test"],
  ["Thrust block", "Concrete poured between a fitting (bend, tee, or cap) and undisturbed soil so water pressure can't push the fitting apart.", "ch9", "thrust restraint"],
  ["Corporation stop", "The valve threaded into the water main where a service line connects.", "ch9", "corp stop|corporation cock"],
  ["Curb stop", "The service line valve near the property line, used to turn a customer's water on or off.", "ch9", "curb valve|curb box"],
  ["Water meter", "A device that measures the volume of water used. Meters should be tested and calibrated on a schedule; the manual says annually.", "ch9 ch4", "meter|meters"],
  ["Water audit", "An accounting of all the water produced compared with water billed and used, to find losses. AWWA's M36 method is the standard.", "ch9", "water loss audit|AWWA M36"],
  ["Non-revenue water", "Water produced but not billed: leaks, theft, meter errors, flushing, and firefighting.", "ch9", "NRW"],
  ["Unaccounted-for water", "The older term for water pumped that can't be matched to billed or known uses; a sign of leaks and meter problems.", "ch9 ch4", "unaccounted for water|water loss"],
  ["Main break", "A rupture in a water main. Isolate it, keep positive pressure where possible, repair and disinfect it, and issue a boil water notice if pressure falls below 20 psi.", "ch9", "broken main|water main break"],
  ["Boil water notice", "A notice telling customers to boil water before drinking it, issued when contamination is possible, such as after pressure falls below 20 psi or a coliform problem. MSDH directs when to issue and lift it.", "ch9 ch6", "boil water advisory|BWN|boil water order"],
  ["Hydropneumatic tank", "A steel pressure tank with an air cushion that smooths pump cycling. It isn't real storage; size it at least 40 times the pump rate in gpm.", "ch9", "pressure tank|hydro tank|hydropneumatic"],
  ["Elevated storage tank", "A tank on a tower that keeps pressure steady, stores water for emergencies and fire flow, and lets pumps run efficiently.", "ch9", "water tower|elevated tank"],
  ["Standpipe", "A tall tank that sits on the ground; only the upper part, above the minimum useful level, counts as usable storage.", "ch9"],
  ["Ground storage tank", "A tank at ground level; pumps must lift water from it into the system.", "ch9", "ground tank"],
  ["Clearwell", "A storage tank at a treatment plant that holds filtered water and provides disinfectant contact time.", "ch9 ch8a", "clear well"],
  ["Overflow pipe", "A pipe that drains excess water from a tank. It must end with an air gap and a screen or flap to keep animals and contamination out.", "ch9", "overflow"],
  ["Tank vent", "An opening that lets air in and out as a tank's level changes. It must be screened and protected from rain.", "ch9", "vent"],
  ["Cathodic protection", "A system that protects steel tanks and pipes from corrosion with sacrificial anodes or a small electric current.", "ch9"],
  ["Tuberculation", "Knobby rust deposits that build up inside old iron pipes, reducing capacity and the C factor.", "ch9 ch4", "tubercles"],
  ["Water age", "How long water has been in the distribution system. Older water loses residual and can carry more byproducts.", "ch9"],
  ["Nitrification", "In chloramine systems, bacteria turning ammonia into nitrite and nitrate, which causes residual loss. Signs: dropping residual and rising nitrite.", "ch9 ch8a"],
  ["Pressure zone", "Part of a distribution system served at one pressure range, often set by a tank's elevation or a PRV.", "ch9"],
  ["Fire flow", "The flow needed to fight fires in an area, delivered while keeping at least 20 psi in the system.", "ch9"],
  ["Residual pressure", "The pressure remaining in a main while water flows from a hydrant during a flow test.", "ch9", "flow test"],
  ["Valve exercising", "Regularly opening and closing valves to keep them working and to find broken or buried ones. The manual recommends doing it annually.", "ch9", "valve exercise"],
  ["Lead service line (LSL)", "A service line made of lead. Systems had to inventory their service lines by October 16, 2024, and most must replace lead lines under the LCRI.", "ch9 ch1", "LSL|lead pipe|service line inventory"],

  /* ---------- Chapter 10: Chlorination equipment & safety ---------- */
  ["Chlorine gas (Cl₂)", "A greenish-yellow, poisonous gas about 2.5 times heavier than air, shipped as a liquid under pressure. It's nearly 100% available chlorine. 10 ppm in air is immediately dangerous to life and health.", "ch10 ch8d", "Cl2|gas chlorine"],
  ["150-pound cylinder", "A chlorine cylinder holding 150 lb, about 92 lb empty; suited to plants under about 0.5 MGD. Store and use it upright. Gas withdrawal tops out around 40 lb per day at room temperature.", "ch10", "150 lb cylinder|chlorine cylinder|cylinder"],
  ["Ton container", "A 2,000-lb chlorine container (about 1,300 lb empty, 3,300 lb full) used on its side. With the valves lined up vertically, the top valve draws gas and the bottom valve draws liquid.", "ch10", "one-ton container|ton cylinder"],
  ["Tare weight", "The weight of an empty container, stamped on it. Subtract it from the scale reading to know how much chlorine is left.", "ch10", "tare"],
  ["Fusible plug", "A metal plug in a chlorine container that melts at 158–165°F to release pressure before the container can burst in a fire.", "ch10"],
  ["Yoke", "The clamp that connects a chlorinator's vacuum regulator, or a manifold, to a cylinder valve.", "ch10"],
  ["Lead gasket", "The soft washer that seals the connection at a chlorine cylinder valve. Use a new one every time you connect.", "ch10", "gasket"],
  ["Vacuum regulator", "The part of a gas chlorinator mounted on the cylinder that opens only under vacuum, so gas stops if a line breaks.", "ch10", "vacuum regulator valve"],
  ["Gas chlorinator", "Equipment that meters chlorine gas under vacuum and dissolves it into water through an ejector.", "ch10", "chlorinator"],
  ["Ejector", "A venturi device where a stream of water creates the vacuum that pulls chlorine gas into solution; also called an injector.", "ch10", "injector"],
  ["Rotameter", "A clear tube with a float that shows the chlorine feed rate in pounds per 24 hours. The manual spells it rotometer.", "ch10", "rotometer|feed rate indicator"],
  ["Booster pump", "The pump that supplies water to a chlorinator's ejector. If it stops, the vacuum collapses and gas flow stops.", "ch10"],
  ["Chlorine emergency kit", "Chlorine Institute leak repair kits: Kit A for 100- and 150-lb cylinders, Kit B for ton containers, and Kit C for tank cars and trucks.", "ch10", "emergency kit|kit A|kit B|kit C"],
  ["Self-contained breathing apparatus (SCBA)", "An air tank and full-face mask that supply clean air; required to enter an area with a possible chlorine leak.", "ch10 ch11", "SCBA|air pack"],
  ["Ammonia test", "Finding a chlorine leak by holding an ammonia-soaked cloth or an open ammonia bottle near it; a white cloud shows the leak. Never pour ammonia on a leak.", "ch10", "ammonia leak test"],
  ["Chlorine leak detector", "A sensor that sounds an alarm when there's chlorine gas in the air of a chlorine room.", "ch10", "gas detector"],

  /* ---------- Chapter 11: Administration & Safety ---------- */
  ["Public Service Commission (PSC)", "The Mississippi agency that regulates service areas for privately owned water systems and water associations.", "ch11", "PSC"],
  ["Service area", "The territory a utility is authorized to serve. The utility must serve everyone in it on equal terms.", "ch11", "certificated area"],
  ["Preventive maintenance", "Scheduled work done to keep equipment from failing, such as lubrication, inspections, and exercising valves.", "ch11", "PM"],
  ["Breakdown maintenance", "Repairs made after equipment has already failed; also called corrective maintenance.", "ch11", "corrective maintenance|reactive maintenance"],
  ["Inventory", "Parts and supplies kept in stock. Count them physically at least once a year, by someone outside day-to-day stores control.", "ch11", "stores"],
  ["Purchase order", "A written order to buy goods. Check it against the vendor's invoice and the receiving report before paying.", "ch11", "PO"],
  ["Accident report", "A written report, filed soon after an accident, meant to find the root cause and prevent repeats rather than assign blame.", "ch11"],
  ["Unsafe act", "Something a worker does that can cause an accident. About 88% of accidents trace back to one.", "ch11"],
  ["Unsafe condition", "A hazard in the workplace, like a missing guard or a slippery floor.", "ch11"],
  ["Personal protective equipment (PPE)", "Gear that protects a worker: gloves, goggles, face shields, hard hats, respirators, and high-visibility vests.", "ch11", "PPE"],
  ["Safety Data Sheet (SDS)", "The manufacturer's 16-section sheet for each hazardous chemical, covering hazards, PPE, first aid, spills, and storage. Keep them where workers can read them.", "ch11", "SDS|MSDS|material safety data sheet"],
  ["Confined space", "A space big enough to enter, with limited ways in or out, and not designed for people to stay in, such as tanks, vaults, wells, and manholes.", "ch11", "permit-required confined space|permit space"],
  ["Atmospheric testing", "Checking the air before entering a confined space, in this order: oxygen (19.5–23.5%), flammable gases (under 10% of the lower explosive limit), then toxics such as hydrogen sulfide and carbon monoxide.", "ch11", "four-gas monitor|gas monitor|air testing"],
  ["Lower explosive limit (LEL)", "The lowest concentration of a gas in air that can burn or explode. Confined space entry requires less than 10% of the LEL.", "ch11", "LEL|lower flammable limit"],
  ["Lockout/tagout (LOTO)", "Shutting off, locking, and tagging every energy source (electric, hydraulic, pressure) before working on equipment so it can't start unexpectedly.", "ch11", "LOTO|lockout tagout|lockout"],
  ["Trench", "An excavation deeper than it is wide. Trenches 5 feet or deeper need a protective system (sloping, shoring, or a trench box) unless dug in stable rock.", "ch11", "excavation|trenching"],
  ["Shoring", "Supports that hold trench walls in place to prevent cave-ins.", "ch11", "trench box|trench shield"],
  ["Competent person", "Under OSHA, someone trained to recognize hazards at a job site who has the authority to correct them, such as inspecting trenches daily and after rain.", "ch11"],
  ["811", "The national call-before-you-dig number. Calling it gets buried utilities marked before excavation.", "ch11 ch9", "call before you dig|Mississippi 811"],
  ["Emergency response plan (ERP)", "A written plan for responding to disasters and threats. Community systems serving more than 3,300 people must certify one to EPA and review it every five years.", "ch11", "ERP|emergency plan"],
  ["Risk and resilience assessment (RRA)", "An evaluation of the risks to a water system from natural hazards and malicious acts, required every five years for community systems serving more than 3,300 people.", "ch11", "RRA|vulnerability assessment"],
  ["Mutual aid", "Agreements between utilities to share people, equipment, and supplies in an emergency, such as Mississippi's WARN network (MsWARN).", "ch11", "WARN|MsWARN"],

  /* ---------- Chapter 12: Cross-connection control ---------- */
  ["Cross-connection", "Any physical connection or arrangement between the potable water system and a source of contamination, through which contaminants could enter.", "ch12", "cross connection|cross-connections"],
  ["Backflow", "Water flowing opposite its intended direction, which can pull contamination into the drinking water system.", "ch12"],
  ["Back pressure", "Backflow caused when pressure on the non-potable side is higher than the potable supply pressure, such as from a boiler or a booster pump.", "ch12", "backpressure|back-pressure"],
  ["Back-siphonage", "Backflow caused by negative pressure (a vacuum) in the supply line, such as during a main break or heavy fire flow.", "ch12", "backsiphonage|siphonage|back siphonage"],
  ["Air gap", "An open vertical space between a water outlet and the flood level of the receiving vessel: at least twice the pipe diameter and never less than 1 inch. The best protection.", "ch12", "AG"],
  ["Atmospheric vacuum breaker (AVB)", "A device that protects against back-siphonage only. It can't be under continuous pressure, and per the manual it must sit at least 12 inches above the highest point of use.", "ch12", "AVB"],
  ["Pressure vacuum breaker (PVB)", "A testable device with a spring-loaded check and an air inlet that protects against back-siphonage only but can stay under continuous pressure; common on irrigation systems.", "ch12", "PVB"],
  ["Double check valve assembly (DCVA)", "Two independent check valves with test cocks and shutoff valves. It protects against back pressure and back-siphonage for low-to-intermediate (non-health) hazards. Head loss is usually under 10 psi.", "ch12", "DCVA|double check|DC"],
  ["Reduced pressure zone assembly (RPZ)", "Two check valves with a relief valve between them that dumps water if a check fails. It protects against both kinds of backflow for high hazards where an air gap isn't practical. Head loss is 10–20 psi.", "ch12", "RPZ|RP|reduced pressure principle assembly|RPBA"],
  ["Relief valve (RPZ)", "The valve in an RPZ's middle zone that opens to the atmosphere to discharge water when a check valve leaks. Water dripping from it means something needs repair.", "ch12", "relief valve"],
  ["Test cocks", "Small valves on testable backflow assemblies where a tester connects gauges.", "ch12", "test cock"],
  ["Hose bib vacuum breaker", "A small vacuum breaker that screws onto an outdoor faucet to stop back-siphonage through a garden hose.", "ch12", "hose connection vacuum breaker|hose bibb vacuum breaker"],
  ["Degree of hazard", "How dangerous a potential backflow would be: high hazard (a contaminant that could cause illness or death) or low hazard (a pollutant that affects only taste, odor, or appearance). It decides which device is required.", "ch12", "high hazard|low hazard|health hazard|non-health hazard"],
  ["Pollutant", "A substance that degrades water quality (taste, color, odor) but isn't a health hazard; a low-hazard backflow concern.", "ch12"],
  ["Containment", "Protecting the public water system by putting a backflow preventer at a customer's service connection (premises isolation).", "ch12", "premises isolation"],
  ["Internal protection", "Backflow devices inside a building at each point of use (fixture isolation), usually required by the plumbing code.", "ch12", "point-of-use isolation|fixture protection|isolation"],
  ["Thermal expansion", "Water's growth in volume as a water heater warms it. In a closed system (with a check valve or backflow device at the meter), it raises pressure; an expansion tank relieves it.", "ch12 ch9", "expansion tank"],
  ["Backflow assembly tester", "A person certified to test backflow prevention assemblies; in Mississippi, MSDH certifies testers. Assemblies are tested at installation, after repairs, and at least once a year.", "ch12", "backflow tester|certified tester"],
  ["Cross-connection control program", "A water system's program to find and eliminate cross-connections: surveys, hazard assessment, required devices, testing records, customer education, and enforcement.", "ch12", "CCC program|backflow program|cross connection control program"],
  ["Potable water", "Water that is safe to drink.", "ch12 ch1", "potable|drinking water"],
  ["Non-potable water", "Water that isn't safe to drink, such as irrigation, process, or reclaimed water.", "ch12", "nonpotable"],
  ["Flood level rim", "The top edge of a sink or tank, where water would spill over. Air gaps are measured from it.", "ch12", "overflow rim"]
];
